### ISSUE TITLE
Vim cursor disappears when running fix imports

### ISSUE THREAD

**Issue by lencioni** [Galooshi/import-js#117]
In a file run the fix imports command. In my Vim, the cursor disappears until I try moving it again. This seems a bit awkward so it might be nice to find a way to prevent it from happening.

I think I've traced it down to this line where we run the eslint command in Importer:

```ruby
out, err = Open3.capture3(command,
                          stdin_data: @editor.current_file_content)
```

but I'm not entirely sure why this has this side-effect. 

This is a really minor annoyance, but I figured I'd log it here in case someone happens to know of an easy fix.

**Comment by trotzig** [comment]
This doesn't happen for me. I recently made this change to my cursors however: https://github.com/trotzig/.vim/commit/bd16e53dc4d42ad148d24e3c4e05d86df5a47f75

**Comment by lencioni** [comment]
Perhaps. I'm using terminus, which does some fancy things with cursors. https://github.com/wincent/terminus/blob/649e8b3811ffeb7f8bdd91ece2e7a194ce5565e9/plugin/terminus.vim#L31-L62

**Comment by lencioni** [comment]
I haven't really noticed this lately (it might still be happening) so I'm going to close this issue out.
