### ISSUE TITLE
Prompt gets garbled when fixing and need to pick for multiple imports

### ISSUE THREAD

**Issue by lencioni** [Galooshi/import-js#137]
If I am working on a file that needs a lot of new modules fixed, and I run fix imports on it for the first time, and multiple modules have multiple matches, the prompt gets a bit garbled. Here's an example:

```
ImportJS: Imported `react` (0.0s)
ImportJS: Pick JS module to import for 'Foo':
1: ../../foo/foo
2: ./Foo
Type number and <Enter> or click with mouse (empty cancels): 2ImportJS: Pick JS module to import for 'Bar':
1: ../../apps/bar
2: ../../foo/bar
```

Notice the line: `Type number and <Enter> or click with mouse (empty cancels): 2ImportJS: Pick JS module to import for 'Bar':`.

**Comment by trotzig** [comment]
Interesting. I'm assuming the prompt gets more garbled as you go along, picking modules to import (since that's handled synchronously).

**Comment by lencioni** [comment]
We should move this issue to the vim-import-js repo

**Comment by lencioni** [comment]
This issue was moved to Galooshi/vim-import-js#2
