### ISSUE TITLE
Goto doesn't work when inside a node_module package

### ISSUE THREAD

**Issue by lencioni** [Galooshi/import-js#178]
This is partly because of a design decision we made earlier to exclude files that are in node_modules when resolving dependencies, and instead rely on package.json. However, when using goto, and you end up inside a package, it would be nice if ImportJS changed context so that the package was the root and resolved files in there. This might be dicey since the package may or may not have Import-JS configuration, so we'll need to figure out what to do with that.

I think this is a very low priority so I'm putting on a help wanted label.

**Comment by lencioni** [comment]
This might actually get pretty hairy with the flatter node_modules that npm 3 produces.

**Comment by z4139jq** [comment]
@lencioni any progress?

**Comment by lencioni** [comment]
@z4139jq no progress that I am aware of. Feel free to submit a PR.
