### ISSUE TITLE
Move import-js to an organization

### ISSUE THREAD

**Issue by lencioni** [Galooshi/import-js#223]
@trotzig [brought up moving import-js to an organization](https://github.com/trotzig/import-js/issues/221#issuecomment-192720145).

> Should we do this under the diffux umbrella btw? It's sort of our common identity. :)

He suggested diffux, but I think it would make more sense to create a new, general organization that could contain import-js, diffux, and other @trotzig @lencioni collaborations. All we need is a good name.

How about galooshi? Or is it galushi? Other ideas?

**Comment by trotzig** [comment]
:laughing: 

galooshi sounds good to me. 

trotzioni
lenzig
joeric
5349miles (distance between Oakland and Stockholm...)
bffs << LET'S PICK THAT ONE!

**Comment by lencioni** [comment]
I've set up the Galooshi organization. @trotzig I think you have the keys to this repo--want to move it when you have some time? https://github.com/galooshi

**Comment by trotzig** [comment]
Yep. I wonder if we should take the opportunity to break out the sublime plugin into its own repo while we're at it (we'd have to send a PR to the Package Control repo anyway, so we might as well do it now).

**Comment by lencioni** [comment]
Yeah, I think that's a good idea. It will clean things up a little, which will be nice. We might eventually have each editor integration have its own repo.

**Comment by trotzig** [comment]
I think that's the direction we're heading.

**Comment by lencioni** [comment]
For a naming scheme, I'd like to suggest EDITOR-import-js, so for sublime it would be sublime-import-js

**Comment by trotzig** [comment]
Sounds good!
