### ISSUE TITLE
Improve error message when eslint cannot be found

### ISSUE THREAD

**Issue by lencioni** [Galooshi/import-js#225]
If eslint cannot be found, we currently just end up with a stack trace like:

```
Error when executing import-js:

/usr/local/lib/ruby/gems/2.2.0/gems/import_js-0.5.1/lib/import_js/importer.rb:190:in `run_eslint_command': env: node: No such file or directory (ImportJS::ParseError)
    from /usr/local/lib/ruby/gems/2.2.0/gems/import_js-0.5.1/lib/import_js/importer.rb:78:in `fix_imports'
    from /usr/local/lib/ruby/gems/2.2.0/gems/import_js-0.5.1/bin/import-js:66:in `<top (required)>'
    from /usr/local/bin/import-js:23:in `load'
    from /usr/local/bin/import-js:23:in `<main>'
```

https://github.com/trotzig/import-js/issues/219#issuecomment-192753539

We should check for `@config.get('eslint_executable')` in the `PATH` before trying to execute it, and if we can't find it then we should show the user a more actionable message.

**Comment by trotzig** [comment]
This shouldn't be an issue anymore since eslint is a dependency of the import-js npm module.
