### ISSUE TITLE
Populate Sublime user settings with default settings the first time they are opened

### ISSUE THREAD

**Issue by lencioni** [Galooshi/import-js#226]
As suggested by @ljharb https://github.com/trotzig/import-js/issues/219#issuecomment-192753539

We could probably also add some comments there to help people do the right thing.

**Comment by lencioni** [comment]
I looked into this some. I was unable to find a built-in way to do this, which makes me wonder if we should do it. Additionally, after we port to JS, I'm not entirely sure we'll still need any configuration, so I say we wait until #221 is complete until we spend time on this, and then re-evaluate.

**Comment by trotzig** [comment]
Sounds good.

**Comment by trotzig** [comment]
I think we can close this. I'm not sure we will need the user setting now that we're on npm. If we do, we can reopen this issue.
