### ISSUE TITLE
Gets fooled by filenames with dots in them

### ISSUE THREAD

**Issue by lencioni** [Galooshi/import-js#229]
If I have a file called `library.extension.js` and I have a variable called `libraryExtension`, import-js is unable to match that up.

**Comment by trotzig** [comment]
Then maybe you should rename "librarararary" to "library"? :wink: 

Can you come up with a repro test?

**Comment by trotzig** [comment]
It looks like this got fixed with the 2.1 release. Can you verify?

**Comment by lencioni** [comment]
I just tested this with 2.1.3 and it seems to be fixed. Thanks!
