### ISSUE TITLE
Scoped imports

### ISSUE THREAD

**Issue by lencioni** [Galooshi/import-js#238]
Sometimes, such as when working in tests, you want to import something but want it at the top of the function you are currently in instead of the top of the file. It would be nice if ImportJS could accommodate this with a new command that works like import word with the exception of where it adds the import statement.

Since there may be many different scopes for where someone might want to place the import (e.g. current function, 2 functions up, current block, etc), I'm not really sure how useful we would be able to make this. Perhaps it could be interactive in some way? Or maybe it puts the import statement into the paste buffer so you can paste it wherever you like?

**Comment by trotzig** [comment]
What if we just place on the line above. Depending on the editor, we can also choose to select the import for easier further manipulation.

**Comment by lencioni** [comment]
Yeah, that might be good enough. Alternatively, #217 might solve this as well.

**Comment by trotzig** [comment]
Yeah, those sound like they could be combined. I think I like #217 more.

**Comment by trotzig** [comment]
I'm going to close this. Let's continue the discussion in #217. I think implementing the behavior there should support this usecase too. 

@lencioni reopen if you disagree.
