### ISSUE TITLE
Use camelCase for configuration instead of snake_case

### ISSUE THREAD

**Issue by lencioni** [Galooshi/import-js#243]
Now that we are entirely in a JS world, it feels really foreign to have stuff in snake_case. I think it would be a good idea to switch over to camelCase before 1.0.0. Thoughts?

**Comment by trotzig** [comment]
Yeah, agreed. To smoothen out the transition, we could support both for a while. But I'm not sure that's important.

**Comment by lencioni** [comment]
Ideally we would support snake_case with a warning for one release and then remove it in the next release. However, I don't think we have a good way of propagating that warning through from the CLI tool to the editor plugins, so perhaps we need to do that first.

It seems like we would want to output this warning in stderr, and then have the editor plugins slurp that up and display it however they see fit. Alternatively, we could add a `warnings` key (or `errors`) to the results JSON blob we output, and then handle it that way. What do you think?

**Comment by trotzig** [comment]
We could use a regular message. Then it would be painful to continue with snakes, but nothing would fail.

**Comment by trotzig** [comment]
...and we don't have to update all plugins

**Comment by lencioni** [comment]
Yeah, I think that sounds ok. We should maybe think about how we want to convey errors or warnings to the editors at some point though.
