### ISSUE TITLE
fixImports doesn't remove unused import if it's the only thing in the file

### ISSUE THREAD

**Issue by trotzig** [Galooshi/import-js#247]
For a file looking like this

```
import foo from 'foo';
```

Running `fixImports` will leave the import untouched. This was likely introduced in 8289e7fce54e (as part of a different bugfix), and is related to how we use a lodash range to represent where imports start and end.

**Comment by lencioni** [comment]
I think this was fixed by 286dfc4b032f6cb2486e508203e553d2689004ff
