### ISSUE TITLE
Speed up Importer test

### ISSUE THREAD

**Issue by trotzig** [Galooshi/import-js#254]
It's quite slow at the moment. We believe the file system access (creating + removing temp files) is the main culprit.

**Comment by lencioni** [comment]
I think a good strategy would be to move the `find` and `egrep` command calls out of findJsModulesFor and into their own module that is well tested. Then, in all of our other tests, we would use a mock for this module instead of making and removing tmp files.

**Comment by trotzig** [comment]
Yep, that's what I've done

**Comment by trotzig** [comment]
Some initial findings. I replaced file system access with a mock, and I'm not getting great improvements:

Before:
```
real    0m40.469s
user    0m19.601s
sys     0m4.314s
```

After:
```
real    0m37.581s
user    0m20.937s
sys     0m4.789s
```

Tests are still failing however, and there might be something expensive done by Jest in such case. I'll continue later to see if I can get tests passing.

**Comment by trotzig** [comment]
Here's that work: https://github.com/Galooshi/import-js/tree/speed-up-tests

**Comment by trotzig** [comment]
I adjusted the speed-up-tests branch a little after finding an interesting thing: we spent most time require-ing modules in each test. Moving imports to the top (and doing some minor adjustments) brought down the test run to half the time it used to take. And then I tackled file system access, which was the second offender. That brought down test times in half again. This is the latest run on my laptop:

```
PASS  lib/__tests__/findMatchingFiles-test.js (0.833s)
PASS  lib/__tests__/Configuration-test.js (1.205s)
PASS  lib/__tests__/ImportStatements-test.js (0.404s)
PASS  lib/__tests__/resolveImportPathAndMain-test.js (0.271s)
PASS  lib/__tests__/JsModule-test.js (0.252s)
PASS  lib/__tests__/ImportStatement-test.js (0.128s)
PASS  lib/__tests__/FileUtils-test.js (0.069s)
PASS  lib/__tests__/Importer-test.js (7.392s)
```

I still want to adjust the last WIP commit a little before this can be merged to master. But it's a great win so far!

**Comment by trotzig** [comment]
I'm closing this. The test is not lightning fast, but it's a lot better than before.
