### ISSUE TITLE
Should be able to specify command file on invocation

### ISSUE THREAD

**Issue by kevinkehl** [Galooshi/import-js#258]
I'm working on the Emacs editor, and it would be helpful to allow for passing the configuration file path as an argument, e.g.

```
importjs word --config ./path/to/config Package ./path/to/file
```

I'm happy to submit a PR for this if everyone thinks it is a good idea.

**Comment by lencioni** [comment]
Can you explain a little more why this would be helpful? I'm thinking that what you probably need to do is ensure that the cwd is properly set, which is important for finding ImportJS configuration and ESLint configuration--so I'm not really sure if this would fully work for your usecase.

**Comment by lencioni** [comment]
For reference, here's how the sublime plugin does it: https://github.com/Galooshi/sublime-import-js/blob/3be5e7ca85c9d27d686a8f9863ee564f2861317f/import-js.py#L68

**Comment by kevinkehl** [comment]
I was inspired by eslint via flycheck for Emacs, which I configure like so:

```
(setq flycheck-eslintrc "~/path/to/.eslintrc.js")
```

but probably it will also work to set the cwd each time. 

It does seem to me that import-js shouldn't be reliant on running from a particular directory (what if I try to use the command line interface from some other directory than my project root?), and I still think this will be useful. The dependency on eslint could be configurable in the .importjs.json pointing to your eslint directory. This would simplify the requirements for the client, but I'm fine dropping this for now.

**Comment by lencioni** [comment]
Perhaps instead of specifying a path to a configuration file, we should add a `--cwd` option? What do you think about that?

**Comment by kevinkehl** [comment]
That sounds reasonable to me.

**Comment by kevinkehl** [comment]
I did this another way in the plugin, closing for now. I may pick this up again as part of the 'run as a process' issue.
