### ISSUE TITLE
What does "Galooshi" mean?

### ISSUE THREAD

**Issue by wincent** [Galooshi/import-js#260]

**Comment by lencioni** [comment]
It's a nonsense word that I caused @trotzig to say once in a bout of impromptu improv.

**Comment by lencioni** [comment]
Going a bit deeper, I guess for me it captures the joy I get from collaborating with @trotzig and it reminds me that this stuff is fun and doesn't have to be so serious all the time. It's the name that we decided to call the GitHub organization to house our collaborations.

**Comment by trotzig** [comment]
😍

**Comment by wincent** [comment]
This sounds reasonable.

You may proceed.
