### ISSUE TITLE
Absolute filename breaks `useRelativePaths`

### ISSUE THREAD

**Issue by janpaul123** [Galooshi/import-js#263]
Running `importjs word router client/actions/mapHandler/mapHandler.js ` results in `import router from '../../js/router';` (correct).

But running `importjs word router /src/remix/core/client/actions/mapHandler/mapHandler.js` results in `import router from '../../../../../../client/js/router';` (incorrect).

Since the Sublime Text plugins calls importjs with the absolute path, this is a pretty significant issue.

**Comment by trotzig** [comment]
Thanks for reporting. I'll look into this, I actually thought we already had code in place that "fixed" this.

**Comment by janpaul123** [comment]
Hm, weird. This was on master though, maybe it regressed?

**Comment by trotzig** [comment]
I think this might be the same issue as #233. I'm investigating.

**Comment by trotzig** [comment]
Okay, looks like this line is broken: https://github.com/Galooshi/import-js/blob/master/lib/JsModule.js#L96 . I have a fix coming up.

**Comment by trotzig** [comment]
Out of curiosity, what does your `lookup_paths` config look like? The regression test case I'm writing is failing, but not the same way. I'm surprised that you even get relative paths, because this bit of code should have prevented it:

```js
    // Ignore if the file to relate to is part of a different lookupPath
    if (!makeRelativeTo.startsWith(this.lookupPath)) {
      return;
    }
```

https://github.com/Galooshi/import-js/blob/master/lib/JsModule.js#L99

**Comment by trotzig** [comment]
I think version 0.7.1 should solve this problem. `npm install -g import-js` to update.

**Comment by janpaul123** [comment]
Cool, thanks, I'll have a look! ☺️ I don't have a lookup path, just `{ "useRelativePaths": true }`.

**Comment by janpaul123** [comment]
Adding a lookup path didn't help btw.

**Comment by janpaul123** [comment]
Just to let you know: this works great. Thanks so much for the speedy fix, my friend. 😸 I was also super happy with the rewrite flag, we've now switched to a unified directory structure (wrote a small script to automatically do renames) and rewriting all imports was super easy! 👍

**Comment by lencioni** [comment]
Awesome to hear!

You know, if you are up for it, you could repay some of the time we've saved you by fixing this issue: https://github.com/Galooshi/sublime-import-js/issues/2 ;)

**Comment by trotzig** [comment]
Good to hear @janpaul123!
