### ISSUE TITLE
Use excludes configuration in findMatchingFiles()

### ISSUE THREAD

**Issue by lencioni** [Galooshi/import-js#277]
Is there any reason we don't use the `excludes` configuration when running the `find` command in `findMatchingFiles()`. It seems that it should be pretty easy to generate a find command that obeys this configuration which could provide some pretty big speed improvements in some cases.

**Comment by trotzig** [comment]
No reason that I can remember. Is the pattern used by `find -path` the same pattern used by miniMatch? In that case, it should be a pretty easy change. We don't really use `excludes` in our codebase, so you're probably better off testing this.

**Comment by lencioni** [comment]
I tried some quick and dirty tests with this on the command line and it didn't seem to offer much speed improvement. I'm going to close out this issue for now.

**Comment by trotzig** [comment]
That's too bad (not making a difference I mean).
