### ISSUE TITLE
declarationKeyword and importFunction don't seem to work correctly with stripFromPath

### ISSUE THREAD

**Issue by lencioni** [Galooshi/import-js#286]
I have the following bit of configuration:

``` json
{
  "appliesTo": "spec/javascripts/**",
  "appliesFrom": "app/assets/javascripts/**",
  "declarationKeyword": "const",
  "importFunction": "myCustomFunction",
  "stripFromPath": "app/assets/javascripts/",
  "useRelativePaths": false
}
```

Which should result in imports from app/assets/javascripts while editing files in spec/javascripts looking like:

``` js
import foo from 'foo';
```

It seems to respect the useRelativePaths config and the stripFromPath config, but not the declarationKeyword or the importFunction. If I remove the stripFromPath config, I get something a bit better:

``` js
const foo = myCustomFunction('app/assets/javascripts/foo');
```

**Comment by trotzig** [comment]
Unrelated to this, but what do you think about ditching the complicated array-based config with `appliesTo`/`appliesFrom` and instead allow the config file to be a regular `js` file? Then we can allow configuration values to be either a value or a function. 

```
{
  declarationKeyword: ({ fileImportedTo, fileBeingImported }) => {
    if (/some-folder/.text(fileImport) {
      return 'const';
    }
    return 'import';
  },
  useRelativePaths: true,
}
```

**Comment by lencioni** [comment]
Oh, that is interesting. I think I like it.

**Comment by trotzig** [comment]
It's really hard to debug these things. It's not clear what value is used to match `appliesTo` and `appliesFrom`. I keep forgetting too.

**Comment by lencioni** [comment]
Yeah, these names aren't the best. Not sure what better names would be though.

**Comment by trotzig** [comment]
The stripFromPath option has been removed. Closing.
