### ISSUE TITLE
Allow configuration to be specified in javascript

### ISSUE THREAD

**Issue by trotzig** [Galooshi/import-js#291]
We currently only support configuration to be specified in JSON. To make the configuration more flexible, we're thinking that some (all?) configuration options can be functions. This will allow for a more dynamic configuration, and is a prerequisite for some of the things we're discussing in https://github.com/Galooshi/import-js/issues/289.

**Comment by rhettlivingston** [comment]
While looking at this, I did some NPM searches and found that there are quite a few packages that try to aid this task. Unfortunately, the one whose code impressed me the most (lightweight, highly flexible, unusually elegant under the hood), [config-one](https://github.com/Klortho/config-one), is in early development and is node 6 only at the moment. But there are a lot of others.

Do you guys know of a package that we could just integrate to do this? How would you feel about leaving the roll-your-own approach?

At the least, there are some great code examples lurking out there, including many of which already support json, js, hjson, etc. and some that have validation.

**Comment by trotzig** [comment]
I don't know of others. I had a quick look at config-one, and it looks promising although not mature enough for my taste. 

I'd be happy to leave the roll-our-own approach. The main thing that complicates things is the local configuration support. If we want an off-the-shelf solution, we'd probably have to step away from that. Which I honestly thinks is a good thing. We'll just have to make sure that we don't accidentally break use-cases. And I think we might have to keep supporting old config files for a while to allow for a smoother transition. We can show a deprecation warning if we find out that you use local configuration.

**Comment by rhettlivingston** [comment]
>The main thing that complicates things is the local configuration support.

Yes. I saw that and understood it enough to imagine the issues, but I need to go try to more thoroughly wrap my head around it.
