### ISSUE TITLE
Tolerate imports/exports below module top-level

### ISSUE THREAD

**Issue by rhettlivingston** [Galooshi/import-js#294]
Meteor 1.3.3 and up has implemented support for conditional and nested imports for its users. This support is critical in an isometric environment and will get used.

```js
if (Meteor.isClient) {
  import { clientonlyFunction } from './client-only-file';
  // code using clientOnlyFunction
  //
}
```

It is not expected that this tool ever actually produce these statements - only that they not cause a problem when present.

They currently cause a problem only because ESLint in its default configuration gives a syntax error and stops parsing when it encounters a nested import such as this. ESLint is utilized by importjs to identify unresolved variables that it can attempt to resolve with a top-level import when fixing imports.

When Meteor first implemented this, we created an issue, babel/babel-eslint#327, that resulted in a PR being accepted by @hzoo, a maintainer of the babel-eslint parser, to add an option, allowImportExportEverywhere, to babel-eslint that just gets passed through to babylon (the underlying parser) which already supported it. babel-eslint is one of the parsers accepted by ESLint. So, our .eslintrc.json files just have to have the following in them to fix this issue:

```json
  "parser": "babel-eslint",
  "parserOptions": {
    "allowImportExportEverywhere": true
  },
```

I believe that if we switch to babel-eslint, we could just turn on allowImportExportEverywhere all of the time. It would have no detrimental side-effects to those not using nested imports. The parser just becomes more tolerant. Even if we don't outright switch (perhaps testing shows it doesn't perform as well), the only option we'd need to provide to the user is an option to utilize the babel-eslint parser instead of espree. There probably wouldn't be any reason not to enable every babel-eslint option. Our purpose is not to enforce code standards, but simply to find the unresolved variables in the code.

This issue was created as a result of discussion in #289.

**Comment by rhettlivingston** [comment]
After further examining this, I have realized that it was a configuration issue. 

Thanks to the resiliency of the design of your ESLint interface, my past effort to implement allowImportExportEverywhere in babel-eslint paid off here as well. As soon as I added the configuration shown above to my .eslintrc.json file within my test project so that ESLint would tolerate conditional imports, import-js tolerated them too.

It may be important that the implications of this be fully understood. **You already use babel-eslint instead of Espree if ESLint is configured to do so.** So, if there is an effect of this on performance, it is already happening in those projects using babel-eslint in their ESLint configuration. Also, though babel-eslint strives to deliver the same tokens in the same order as Espree in order to not break ESLint rules, it does not always succeed.

**Comment by rhettlivingston** [comment]
Note that a project not otherwise using ESLint and utilizing experimental features provided by babel may need to provide an appropriate .eslintrc.json file in order for your product to succeed in identifying unresolved variables. Essentially, it seems .eslintrc.json is part of your configuration. That may deserve documentation within your README.

**Comment by trotzig** [comment]
You've made a correct examination @rhettlivingston. Having import-js use the eslint configuration from your local project is mostly important for getting access to all global variables. Without it, ImportJS would treat global variables as undefined and try to import them. The integration isn't free from trouble however. If your project uses a version of eslint that's incompatible with the version ImportJS uses, things will fail. I've thought about reverting local eslint config support and just ignore the fact that globals will be imported (and perhaps add a `globals` configuration option in ImportJS instead).

**Comment by rhettlivingston** [comment]
I think that being able to close this issue points out the upside of your approach.

With the local config support, you're picking up globals and anything else they've included to get ESLint to operate on their project. So, yes you're a little exposed to ESLint problems. Without it, you'd have to add configuration for globals, for switching to babel-eslint, and for specifying babel-eslint options. That is also an exposure of a sort.

I think that you'll find better balance if you document your use of the project's ESLint configuration in your README so that users who aren't using ESLint and might need to configure globals or other ESLint options aimed at allowing experimental syntax to be parsed won't be in the dark as to how to get import-js to work better in their project.

Alternatively, have you considered adding an ESLint configuration section to your configuration that is purely passed through? That would minimize your exposure to ESLint changes, eliminate the need for you to address every ESLint option your users might need to specify, and separate you from the project's more general ESLint configuration. This would still involve documentation in your README. The advantage I think is that the ESLint configuration would become more explicit and intentional as opposed to just incidental or accidental. The disadvantage is that users might see it as duplicative.

**Comment by trotzig** [comment]
> I think that you'll find better balance if you document your use of the project's ESLint configuration

Good point, I'll try to add that soon. 

> Alternatively, have you considered adding an ESLint configuration section to your configuration that is purely passed through?

Do you mean something like this?

```js
{
  declarationKeyword: 'const',
  eslintConfig: {
    plugins: [
      // ... etc
    ],
  }
}
```
I think that could confuse more than it would help, although I agree with it being more explicit and intentional. 

I'm glad to have you involved @rhettlivingston! You bring a lot of good ideas to the table, and you make us challenge our own decisions in a way that we wouldn't do otherwise. I'm excited to take ImportJS to the next level by making it (better) compatible with meteorjs.

**Comment by rhettlivingston** [comment]
Thank you! Stretching to cover a different community can be good or bad. Hopefully by concentrating on changes that generalize and enable instead of specializing, it will all be good!

> Do you mean something like this?

Yes, pretty much. The idea came up because we actually recommend in the Meteor guide that our users configure ESLint by including the eslintConfig section inside the package.json file. So I'm used to seeing it lumped into another configuration file. If you were to go that way, I might even go ahead and put the parser and parserOptions above in the meteor environments file. 

Of course, to avoid breaking, you'd have to go a route that continues to use the user's ESLint configuration unless you were explicitly given a configuration. That's a huge downside of the whole thought. i.e. it does nothing to solve the problems that you've encountered in your existing approach except to give another way out when they are encountered.

There may be an actual performance advantage in that it could eliminate plugins that aren't useful to your needs. We recommend at least four ESLint plugins that you don't need. They've got to have some startup and other overhead.

I actually lean against this whole idea though it's intriguing. Simply had a thought. It's a pure judgment call.
