### ISSUE TITLE
Reimplement environments using configurations

### ISSUE THREAD

**Issue by rhettlivingston** [Galooshi/import-js#296]
Probably prerequisites / complements to this include:
 - Allow configuration to be specified in javascript #291
 - Allow environments to specify full set of configuration options #290
 - Move environment core modules into configuration #292

Basically, the thought is that the implementation of the two environments we have and all future environments should be accomplished as configuration files. When we encounter `"environments": "node"],`, it should simply be converted into a load of the configuration file that defines the node environment.

User's will easily be able to define their own configuration files accomplishing the same type of thing for new environments without this. But I think using it internally helps to vet the capability and provides examples of what can be done if import-js uses the same approach to implement its built-in environments.

Also, to support users in sharing their environment definitions to the community via NPM, we could provide a very direct means of tying them in. This could be as simple as... when we encounter an environments string we don't recognize, try to find an NPM module with the same name and "require" a config file from within the NPM module. If successful, process it. Then, users could simply "npm add --save-dev import-js-env-xxx"  and add "import-js-env-xxx" into their "environments" list to tie it in.

**Comment by trotzig** [comment]
This is a good plan. I have mixed feelings about the auto-resolve of unknown environments. I remember being confused about the way eslint does the same thing. But I think it's okay.

**Comment by rhettlivingston** [comment]
I think that the spirit of this issue has been resolved. I believe it started with 7d8dfbf and numerous commits since that time have been extending the environment configurations that were created then.

The extension of this feature to support plugins can be punted to some future enhancement.

Closing #296.
