### ISSUE TITLE
namedExports with node modules being imported as relative paths

### ISSUE THREAD

**Issue by joefiorini** [Galooshi/import-js#304]
### Reproduce

In my `.importjs.json` I have the following:

``` json
{
  "namedExports": {
    "app/bundles/get_rate_flow/utils": [
      "logValue",
      "isNil",
      "actionType"
    ],
    "app/bundles/get_rate_flow/reducers": [
      "loadFlow",
      "gotoFirstUnfinishedStep"
    ],
    "react": [
      "Component",
      "PropTypes"
    ],
    "react-redux": [
      "connect",
      "Provider"
    ],
    "reselect": [
      "createSelector",
      "createStructuredSelector"
    ],
    "enzyme": [
      "mount"
    ]
  }
}
```

I'm running the command:

`importjs word Component app/bundles/get_rate_flow/components/step.jsx`
### Expected

To have the line `import { Component } from 'react';` in the referenced file
### Actual

Has the line `import { Component } from '../../../../react';` instead; note it's using relative paths even though `react` is in my `package.json`.

I also tried this with:

`importjs word connect app/bundles/get_rate_flow/components/step.jsx`

and got a similar result (`import { connect } from '../../../../react-redux';`).
### Notes

I upgraded from `0.8.0` to `1.0.1`. This was not an issue until after I upgraded.

**Comment by trotzig** [comment]
Interesting, thanks for reporting. I'm having issues reproducing this locally. I'm testing with this in my importjs config:

```json
  "namedExports": {
    "eslint": [
      "foo"
    ]
  }
```

and it correctly produces the right import statement:

```js
import { foo } from 'eslint';
```

Can you share your `package.json` and `.importjs.json` here?

**Comment by lencioni** [comment]
Can you also share the output of `importjs --version`?

**Comment by lencioni** [comment]
I ran into this as well recently in a test project. I believe it happens when the package is not in your dependencies.

I fixed it here by adding the packages to dependencies. https://github.com/lencioni/import-js-simple-project/commit/24adeadec8ce4bbd0818c3f027c868247d869099

**Comment by joefiorini** [comment]
@trotzig [Here's a gist of a snippet of my package.json](https://gist.github.com/joefiorini/d84671fe411cdf35f4e51a613a13362f) showing deps/devDeps (it's a work project, so don't want to include any sensitive details). Let me know if you need to see anything else.

My `.importjs.json` is included above, but I'm adding to [the above-linked gist](https://gist.github.com/joefiorini/d84671fe411cdf35f4e51a613a13362f) as well.

And `importjs --version`:

> 1.0.1

**Comment by joefiorini** [comment]
@lencioni Both of the examples I showed are for libraries referenced in my `package.json`.

**Comment by lencioni** [comment]
Hmm, that all seems fine to me. Can you set up a small repro case in a repo somewhere?

**Comment by trotzig** [comment]
is it possible that you're running importjs from a different folder than where the package.json is located?

**Comment by trotzig** [comment]
Alternatively, can you try running this from the same folder:

```js
// test.js
console.log(require.resolve('react'));
```

```bash
node test.js
```

**Comment by trotzig** [comment]
@joefiorini: did things get resolved or are you still seeing the same issue?

**Comment by trotzig** [comment]
Before doing so, could you try the `require.resolve` snippet I suggested above? I suspect we're getting a path returned that doesn't start with `node_modules`. It would also be helpful if you could post back what version of node you are running.

**Comment by joefiorini** [comment]
@trotzig It would appear I'm running node v5.0.0

**Comment by linchen2chris** [comment]
my solution is 1) use absolute path 2) then stripFromPath
`
 "useRelativePaths": false,
  "stripFromPath": "src/",
`

**Comment by trotzig** [comment]
Interesting @linchen2chris. Would you get the same results if you used this config instead?

```json
"useRelativePaths": false,
"lookupPaths": ["src"],
```

**Comment by linchen2chris** [comment]
@trotzig  no, I didn't get the `import { Component } from '../../../../react';` 
actually
1) the modules in node_modules always work fine for me, I can get `import {Component, PropTypes} from "react"` correctly. 
2) I write many modules in  src/my_components/, I want import them as ` import {xxx} from "my_components"` rather then `import {xxx} from "../../../../src/my_components"` so I use the solution
`"useRelativePaths": false, "stripFromPath": "src/"`

**Comment by trotzig** [comment]
Interesting, I'm surprised to see those long relative paths. Could you play around a little with `require.resolve('some_component')` to see why ImportJS gets the relative path wrong? Also, could you provide a little more information about your OS, Node version, .importjs.json and such? Thanks for helping out!

**Comment by trotzig** [comment]
With version 2.1, we now automatically find named exports. I'm going to close this, though I'm interested to hear if the new version is able to find all those named exports that you previously listed in config.
