### ISSUE TITLE
Support configuration comments

### ISSUE THREAD

**Issue by rhettlivingston** [Galooshi/import-js#318]
There are good reasons why ESLint and many other development tools that work on code support inline directives in the form of comments. Cases will arise where a user has a desire to change importjs configuration on a per-file basis. For example, perhaps they want groupImports to be generally active but have a single file where changing the order of the imports would cause a malfunction. In that case, it would be nice to be able to do something like

// import-js { groupImports: false }

**Comment by lencioni** [comment]
We have deprecated JSON configuration in favor of JS configuration, which allows comments. Closing this issue out.
