### ISSUE TITLE
Handle Files within modules

### ISSUE THREAD

**Issue by nmn** [Galooshi/import-js#320]
Many packages are collections of files, instead of a single file. Currently these don't get imported at all.

Make it possible to add such packages to the `lookupPaths`.

For example: `node_modules/lodash/` should let you import all the individual functions.

**Comment by trotzig** [comment]
Hi @nmn, and thanks for using the tool! Work is ongoing to support automatically detecting multiple exports from package dependencies, mostly in #199. In the meantime, you can specify all the lodash dependencies using `namedExports` or `aliases`:

```json
"namedExports": {
  "lodash": [
    "throttle",
    "debounce",
    ... and so on
  ]
}
```

```json
"aliases": {
  "throttle": "lodash/throttle",
  "debounce": "lodash/debounce",
  ... and so on
},
```

I'm going to close this and refer discussions to #199 instead. Feel free to reopen if you think that's the wrong move!
