### ISSUE TITLE
configure namedExport in .importjs.json

### ISSUE THREAD

**Issue by linchen2chris** [Galooshi/import-js#325]
I have a a.js file, it export a few functions like this:
```js
export function b() {
}
export function c() {
}
...
```
I have to type these functions one by one to namedExport like
```json
"namedExports": {
  "a": [
    "b", 
    "c",
    ....
  ]
}
```
can I add all exported functions only one time

**Comment by trotzig** [comment]
Good question! This is being discussed in more detail in #199. It's on our radar. :)
