### ISSUE TITLE
stripFromPath configuration modifies paths too early

### ISSUE THREAD

**Issue by lencioni** [Galooshi/import-js#327]
I've noticed a weird symptom where my custom configuration only sometimes applies to my imports. By adding some logging in my .importjs.js file, I noticed that sometimes the path to the imported module would be like `'./path/to/foo.js'` while other times it is `'path/to/foo.js'`.

In this configuration, I happen to have a `stripFromPath` configuration that removes part of the path under certain conditions. I noticed that the `./` disappears after this is run. This leads me to believe that we are handling this at the wrong time.

For the purposes of configuration, paths should always be the same. I haven't had time to dig into this, further, but I think it probably makes sense to strip from path somewhere else. I think we need to take a more holistic look at how all of these parts fit together, come up with a good plan, and straighten it out.

**Comment by lencioni** [comment]
I think we should remove `stripFromPath` and `stripFileExtensions` options in favor of `moduleNameFormatter`.

**Comment by trotzig** [comment]
It's a little tricky to remove `stripFileExtensions` since people probably want that as a default. If they implement `moduleNameFormatter` without taking that into account, there might be confusion. I see that you didn't touch that in your work above, did you come to the same conclusion?

**Comment by lencioni** [comment]
We have removed this option in favor of `moduleNameFormatter`, so I think I'm going to close this issue.
