### ISSUE TITLE
filePath can't get set to mainFile in JsModule

### ISSUE THREAD

**Issue by rhettlivingston** [Galooshi/import-js#335]
Noted that this "problem" that was mentioned before in #169 discussions still needs to be fixed. First, to verify that it is needed code and to prevent regression, a test needs to be created that fails on whatever true problem it likely causes.

In jsModule I encountered the following while stepping through code. "startsWith" didn't look at all right.
```js
      if (!this.filePath.startsWith('/package.json')) {
```
I found that it has been in the code since the conversion to JavaScript. Before conversion it was
```js
        return @file_path unless @file_path.end_with?('/package.json')
```
so it's definitely wrong.

**Comment by trotzig** [comment]
Thanks for the reminder. I'm on it. It looks like we have tests that validate its intended behavior, and they still pass. So we must be handling that case elsewhere.
