### ISSUE TITLE
Handle eslint errors better

### ISSUE THREAD

**Issue by trotzig** [Galooshi/import-js#348]
This came out of a discussion over at the sublime plugin. When eslint fails, the sublime plugin became unusable.  

https://github.com/Galooshi/sublime-import-js/issues/14

**Comment by Uelb** [comment]
Hey, it seems that this ST plugin is a great help for developers 👍 , I can't seem to make it run with my configuration and I think it's linked to this issue. Is there a workaround that could help me getting started on using this plugin ?

**Comment by trotzig** [comment]
Hi @Uelb, thanks for giving import-js a spin! What version of eslint are you on? It could be a version mismatch causing this issue. Import-js is on version 3. 

I don't have a great workaround for now other than either making sure that you're on the same eslint version. Or you can stop using the `fix` command and instead individually importing variables (although that would make the tool less usable). 

If you can think of ways to make this better, we'd love some input. It would be great to replace the dependency on eslint and instead use a js parser directly. But that comes with its own set of issues. Eslint has been serving us well, but it's probably time for a change.

**Comment by Uelb** [comment]
The eslint I use is v3.8.1. I can't figure out how to use the word import on Sublime Text but I'll read issues on the sublime related repo and open an issue if it's worth it.

**Comment by thecotne** [comment]
@trotzig `import-js` is on `eslint@^2.8.0` according to `npm show import-js`

but according to this repo it's on `eslint@^3.0.0` https://github.com/Galooshi/import-js/blob/master/package.json#L67

also latest version in npm is `1.1.2` but in releases of this repo latest is `1.1.1`

so this is issue with release process 

as a workaround 

i have installed it from github and built manually 

```bash
sudo npm install -g Galooshi/import-js
cd /usr/lib/node_modules/import-js
sudo npm install
sudo npm run build
```

**Comment by trotzig** [comment]
The current master branch hasn't been released yet. We're working towards a 2.0 release, but it's been a little slow lately. 

I'm to blame for the missing 1.1.2 release notes. I just added them. 

I'm hoping to remove the eslint dependency in 2.0 and instead rely on an internal ast parser to find unused/undefined imports.

**Comment by trotzig** [comment]
I just wrote a commit to remove the eslint dependency: https://github.com/Galooshi/import-js/commit/18e541c7f38c0c33e522bd5338fca20c5bcabae3. I will do my best for this to land on the master branch and be shipped as a new version soon.

**Comment by trotzig** [comment]
Version 2.0 should resolve this as it removes the dependency on eslint. I'd appreciate if you could take it for a spin!
https://github.com/Galooshi/import-js/releases/tag/v2.0.0
