### ISSUE TITLE
Imports without semicolons not treated as imports

### ISSUE THREAD

**Issue by trotzig** [Galooshi/import-js#352]
Originally reported here: https://github.com/Galooshi/atom-import-js/issues/8

I'm moving the issue to the main project as it affects all clients. 

Given this content

```js
import AppView from './AppView'

const Test = AppView;
```

If you import AppView, you end up with duplicate import lines. One with semicolon (added by import-js) and one without (the original).

```js
import AppView from './AppView';

import AppView from './AppView'

const Abc = AppView;
```

The original bug report is for the atom plugin, but I have confirmed this bug to exist in the vim plugin as well.

**Comment by trotzig** [comment]
I've added the "Help wanted" label since I'll probably not have time to fix this any time soon, plus I'm not really affected by it (we enforce trailing semicolons with help from eslint).

**Comment by thebarty** [comment]
yeah that would be really nice to have. My whole project got rid of those semicolons

**Comment by dcporter** [comment]
@trotzig any chance you could point me to the spot(s) in the codebase where the "these are the extant imports"; "this one matches" logic lives?

**Comment by trotzig** [comment]
This is the main regex used to match imports: https://github.com/Galooshi/import-js/blob/ae73c764682d1ff9925575d0fb3969886cc6de9f/lib/ImportStatement.js#L23. Though there's a pre-processing step that assumes semicolons higher up in the hierarchy: https://github.com/Galooshi/import-js/blob/ae73c764682d1ff9925575d0fb3969886cc6de9f/lib/findCurrentImports.js#L51

However, I'm about to kill both of those regexes in favor of a real parser. That work is ongoing in https://github.com/Galooshi/import-js/tree/better-parsing. I can't promise anything, but I'm hoping to release that in a 2.0 in the coming month.

**Comment by dcporter** [comment]
Hi sorry — can you elaborate on how the `importStatementFormatter` option should be used to let the plugin know that `import { observable } from 'mobx'` present in my code matches its intended `import { observable } from 'mobx';`, and prevents it from adding it again? Appreciated!

**Comment by trotzig** [comment]
Of course, sorry for leaving you in the dark here.

With 2.0, import statements without semicolons at the end are already recognized. The issue that you can solve with `importStatementFormatter` is that import-js will automatically add the semicolon when it constructs new import statements. You should be able to use something like 

```js
// .importjs.js
module.exports = {
  importStatementFormatter: function({ importStatement }) {
    return importStatement.replace(/;$/, '');
  },
}
```

**Comment by dcporter** [comment]
Oh that's versatile and fantastic! Does that replace the flags from v1, or does the default importStatementFormatter make use of them?

**Comment by trotzig** [comment]
I'm assuming that you mean `stripFromPath` and `lookupPaths` when you say flags. Is that correct? 

Most of the time, you're better off using a `moduleNameFormatter` instead of the new `importStatementFormatter`. This is because `moduleNameFormatter` is restricted to only change the string used as the module name in the import statement. `importStatementFormatter` operates on the full `import foo from 'foo';` string.

**Comment by dcporter** [comment]
Re: flags — I swear there was a flag for including semicolons or not, that's what I meant. But I just checked the readme for v1.1.2 and no mention of it, so I'll assume that was a fever dream.

So the upshot is that the new version parses extant imports better, and we now have better control over the imports the plugin adds. v2.0 sounds like a big win, thanks so much for it!
