### ISSUE TITLE
Need a new version pushed to npm

### ISSUE THREAD

**Issue by kevinkehl** [Galooshi/import-js#354]
importjs is currently broken using updated eslint configs (such as eslint-config-airbnb) without the update to eslint^3.0.0 (https://github.com/Galooshi/import-js/commit/a6f4c67dd7ff30d96ba99c3c33dd8755a52035d5). We should push a new (patch?) version.

**Comment by trotzig** [comment]
I don't have all the context here. The commit you linked to seems to update the eslint-plugin-react package, not eslint. 

Is import-js broken for a particular project? 

We're in the middle of a transition off of eslint. I hope to release something soon (ongoing here: https://github.com/Galooshi/import-js/tree/better-parsing), but right now the current `master` branch isn't in a releasable state. 

If you want to make a quick-fix, there's the `maintenance-v1` branch. I've used that at least once before for a bugfix release.

**Comment by kevinkehl** [comment]
Apologies, wrong commit link. https://github.com/Galooshi/import-js/commit/80c378b072fde9f098c20e64905066faf6d1bebc.

Some more context: 

I was testing the changes to the emacs plugin, and was having issues getting the 'fix' command to work (even in the CLI). I had created a new project using [create-react-app](https://github.com/facebookincubator/create-react-app) followed by an `eslint init`, selecting the airbnb plugin (which has reasonable config). I received the following error:

```
Kevins-MacBook-Air:test-import-js kevinkehl$ importjs fix src/App/index.jsx
/Users/kevinkehl/.nvm/versions/v6.9.1/lib/node_modules/import-js/node_modules/eslint/lib/config/config-file.js:402
            throw e;
            ^

Error: /Users/kevinkehl/.nvm/versions/v6.9.1/lib/node_modules/eslint-config-airbnb/node_modules/eslint-config-airbnb-base/rules/es6.js:
	Configuration for rule "arrow-parens" is invalid:
	Value "as-needed,[object Object]" has more items than allowed.

Referenced from: /Users/kevinkehl/.nvm/versions/v6.9.1/lib/node_modules/eslint-config-airbnb/node_modules/eslint-config-airbnb-base/index.js
Referenced from: airbnb
Referenced from: /Users/kevinkehl/projects/test-import-js/.eslintrc.js
```

which stems from use of the local eslint at 2.x.

The current master branch already fixes this with the commit above to bump eslint to 3.x  (and I worked around it by using a local version with `npm link`). I'm not blocked at the moment, but I figured this was an easy fix for setting up new projects since it should just be an npm publish.

**Comment by trotzig** [comment]
Cool, thanks. The problem with the version bump is that it breaks projects using an earlier eslint (I believe). Plus master is full of other changes as well. Expect this to be fixed in 2.0, coming sooooooooon.

**Comment by kevinkehl** [comment]
OK!

*waits excitedly*

**Comment by mike623** [comment]
facing that problem. Is there any updates?

**Comment by trotzig** [comment]
I'm hoping to release 2.0 during the day. I just need to run some local testing before I do that. Thanks for being patient!

**Comment by trotzig** [comment]
I would appreciate if you could take 2.0 for a spin and see if it works out. 
https://github.com/Galooshi/import-js/releases/tag/v2.0.0
