### ISSUE TITLE
Allow Importer to accept config options for its Configuration

### ISSUE THREAD

**Issue by dcporter** [Galooshi/import-js#359]
Currently, Configuration’s constructor (and by extension, Importer itself) only knows how to load configurations from disk. I need the ability to provide a config object directly at runtime *instead of* looking at the disk — and since only Importer is externally visible, I believe I need to be able to pass it into Importer's constructor.

My use case is: I need to provide a large and dynamic `namedExports` list to `import-js`, and I need to be able to do so without thrashing the disk with it as it changes.

Thanks again for the great resource!

**Comment by trotzig** [comment]
You have a few options here: 
- Wait for 2.1.0 to be released. This version will automatically find most named exports. Install import-js `2.1.0-beta.2` and give it a spin if you want to help out as a beta tester!
- Implement `namedExports` as a function returning the named exports. Look at https://github.com/Galooshi/import-js/blob/master/lib/environments/meteorEnvironment.js for inspiration. 

Let me know if none of those options work out!

**Comment by dcporter** [comment]
The function is a powerful feature, I didn't know about it! That should help me get moving in the mean time. Super looking forward to v2.1! Grabbing the beta now.

I think I would still like to request the pass-in-a-config feature, as it would simplify the flow of feeding in my own named export list (or any other config) to an Importer. I'm looking to build on top of this project in Node, and I don't think I'm going to be able to use it if it means making users add a file with a particular function in it to their project.

In terms of implementation, I think it would be fine to add a fourth argument to `Importer`'s constructor, and pass it through as a third argument to `Configuration` [here](https://github.com/Galooshi/import-js/blob/find-named-exports/lib/Importer.js#L31) — if I'm in a position to pass in my own configuration hash, then I'm in a position to pass in a working directory too (and probably want to). For my purposes I would obviously want Configuration to [bypass `loadUserConfig`](https://github.com/Galooshi/import-js/blob/find-named-exports/lib/Configuration.js#L183-L189) if the config is passed in. Of course I'm biased since it's my feature request, 😁, but it looks to me like a simple and fairly unintrusive change. I'm very sorry that I'm not simply submitting a PR directly, but I'm unfortunately not in a position to do so.

Obviously understood if I'm missing something, or if knowledge of future plans makes this more intrusive than it looks, in which case please feel free to defer or close the issue! Either way, thanks again for your super useful (and rapidly improving!) importer tool.

**Comment by trotzig** [comment]
I'm happy you're finding the tool useful. Would you mind sharing a little about the tool you are building on top of import-js? It might help us better understand the use-case. I have no objections to adding a fourth argument to `Importer` at this point (although there might be an even better interface we can provide for people wanting to integrate more directly with the tool).

**Comment by trotzig** [comment]
Right now, the `find-named-exports` branch is ignoring node_modules in search of named exports. That's a blocker for the release though, and I've just been pushing it because it's a little trickier than I first thought. 

Named exports are cached in an sqlite database in a somewhat simple format, so you could either query it directly or you can use the `ExportsStorage` module and its interface.

**Comment by dcporter** [comment]
Yeah I saw ExportsStorage, it's tidy. I'll poke at it and see what I can use. Importing from deep in a package always feels a little dangerous, but you've got a ton of useful stuff in here!

Great news re: the package exports. That's really huge. I'm curious what's trickier than expected about the package exports? I understand the problem space as "what is this package's main file" and "what does that main file export" — is there more to it than that, or are those two steps just more complicated than they sound?

**Comment by trotzig** [comment]
Finding the main file isn't the issue, that's easy. The problem is that most of the time, that main file is simply pointing at (importing/requiring) some other file. Here's `react` for instance: 

```
'use strict';

module.exports = require('./lib/React');
```

I'm trying to avoid having to execute the code in order to find exports. Parsing should be enough. But in these cases, we'd have to know to parse the other file. Not that this is terribly hard to implement, I just haven't had the time yet. 

If you want to contribute, changing `findExports.js` to also follow imports/requires would be a great addition to the `find-named-exports` branch. This is likely what I'll do next, but first I'm taking a few days off from coding. ⛷ ☕️ 👶

**Comment by dcporter** [comment]
> Parsing should be enough.

I think so too — `find-named-exports` is already doing that for files in the local project directory, so it just needs to feed the package's main file through the same pipe.

I wish I could help — I'm afraid I'm not in a position to contribute at this time ( :( ). Happy skiing and 👶ing! Two exhausting efforts.

**Comment by dcporter** [comment]
Closing this until I have a more concrete use case (i.e. probably forever). Viva v2.1 🎉
