### ISSUE TITLE
FlowType: import types deleted

### ISSUE THREAD

**Issue by kylpo** [Galooshi/import-js#360]
Not sure if this is a configuration question or feature request, but with a file like:

```js
import type { Counter } from 'types/counter'

type Props = {
  counter: Counter,
}

...
```

When :ImportJSFix is run (from vim in my case), the `import type { Counter } ...` line is removed from imports. Is there a way for importjs to "see" counter in the Props declaration? Or maybe just a global config for importjs to not delete "unused" imports?

Note: this is not specific to `import type ...`. If I remove `type` from the import, the import line is still deleted.

Thanks for any help - really loving this tool!

**Comment by kylpo** [comment]
Ah, sweet! Just tried out `2.1.0-beta.2` and it works without deleting the import. Closing...

**Comment by trotzig** [comment]
Thanks, sorry for that bug. I'm glad the beta release helped. Let me know if you notice any weird things with it. One thing that I should note is that you're probably best off installing watchman. 2.1.0-beta has code in place to keep a local cache of exports from files, and if you don't use watchman you'll end up polling the file system. Which is fine for smaller projects (<400-500 files), but not great  for bigger projects.

**Comment by kylpo** [comment]
Right on - thanks! All is working well, and I do have watchman installed.
