### ISSUE TITLE
Beta errors on empty variable declarations

### ISSUE THREAD

**Issue by dcporter** [Galooshi/import-js#364]
Any file containing an empty variable declaration like `let foo;` will throw "TypeError: Cannot read property 'type' of null" [here](https://github.com/Galooshi/import-js/blob/find-named-exports/lib/findExports.js#L55), as uninitialized variable declarations have an `init` of `null` (see [AST](https://astexplorer.net/#/X5GstEcJRl)).

**Comment by trotzig** [comment]
Thanks!

**Comment by dcporter** [comment]
Thanks too!

This fix solved a bunch of cases but moved the error down-file in this case:

```js
let foo;

foo = "hi";
```

When it gets to the second line, I'm getting "TypeError: Cannot read property 'name' of undefined" [here](https://github.com/Galooshi/import-js/blob/find-named-exports/lib/findExports.js#L39), because `left` has neither `object` nor `property`. AST [here](https://astexplorer.net/#/5biReaU1kp).

**Comment by trotzig** [comment]
Ah, sloppy. I'll have a fix for that tomorrow. Thanks!

**Comment by trotzig** [comment]
Fix is here: https://github.com/Galooshi/import-js/commit/f7e504839fdc3042f55aaeb05dc8f01230ff07ff
