### ISSUE TITLE
No JS module to import for.

### ISSUE THREAD

**Issue by Rybadour** [Galooshi/import-js#368]
I've installed importjs from NPM and it seems to run without error however I am getting errors indicating it can't find modules in my working directory.

Upon further inspection I see that it seems to be constructing the paths wrong because I see this in /tmp/importjs.log:

```
1486661423481 DEBUG Processing /local/home/gameboy/workspaces/WORKSPACE/src/PROJECT/tst/utils/UniqueKeyUtilsTest.js
1486661423481 ERROR ENOENT: no such file or directory, open '/local/home/gameboy/workspaces/WORKSPACE/src/PROJECT/local/home/gameboy/workspaces/WORKSPACE/src/PROJECT/tst/utils/UniqueKeyUtilsTest.js'
```

As you can see it's duplicating the absolute path for some reason.

My .importjs.js file is as follows:

```
module.exports = {
      logLevel: 'debug',
      useRelativePaths: false,
 
      moduleNameFormatter: function ({ moduleName, pathToCurrentFile }) {
          return moduleName.replace(/^js\//, '');
      },
  }
```

Any idea what I can do to fix?

**Comment by trotzig** [comment]
Thanks for the report! I found the same thing yesterday, and there's a PR to fix it: https://github.com/Galooshi/import-js/pull/367

To work around the issue, you can [install watchman](https://github.com/Galooshi/import-js#speeding-it-up). Or you can help me release a new version by reviewing the code in PR #367. Or do both. 😄

**Comment by Rybadour** [comment]
Wonderful! Thank you.

I've installed Watchman but it seems to have the exact same issue. Do I have to stop some previous daemon to make it switch to using Watchman?

**Comment by trotzig** [comment]
Most likely, yes. What editor are you using? You might also have to run `rm $(importjs cachepath)` from the root project dir.

**Comment by Rybadour** [comment]
I'm using Vim.
At work we don't seem to have access to packages like watchman so I'll have to wait on the fix.
I tried installing just the npm fb-watchman package but that doesn't seem to have the binaries we need.

**Comment by trotzig** [comment]
You're right, the `fb-watchman` package doesn't include the binaries. Import-js already depends on that module too. 

I'll cut a release asap so that you can try it out.

**Comment by trotzig** [comment]
Okay, I just published 2.1.1. Let me know how it goes!

**Comment by Rybadour** [comment]
Excellent, works like a charm!

**Comment by trotzig** [comment]
Great! Honestly, I haven't spent too much time on the non-watchman variant of import-js. It uses a polling approach (30s intervals), which means that results will not always be up-to-date. Let me know if it's very painful to use, there might be a better solution out there.

**Comment by Rybadour** [comment]
It can be quite painful. Often times I'll create a new file to use in another and I want to create the import right away so I don't forget to later but it sucks to wait upwards of 30 seconds.

**Comment by trotzig** [comment]
I understand. I've been considering having a hard dependency on Watchman for that reason, but it sounds like that's not an option for you. Would you mind giving some more context on why you wouldn't be able to install it at work?

I'll look into switching out polling for a node-only watcher soon. Thanks for letting me know about your situation.

**Comment by lencioni** [comment]
If you are on OS X, we could probably do something with https://www.npmjs.com/package/fsevents
