### ISSUE TITLE
`Fix all imports` removes star imports (* as)

### ISSUE THREAD

**Issue by asfktz** [Galooshi/import-js#369]
Hi,
how are you? 😊

First, I want to thank you so much for the 2.0 release,
Auto import named exports is amazing!

Lately, I encountered a regression where calling `importjs: fix all imports` removes all import expression with `* as` syntax

I'm not 100% sure, but I believe that it starts with `v2.0.0`, where earlier versions (`v1.1.2`) works fine.

Steps to reproduce:
1. Create 2 files:

```js
// api.js

export function get () {
  // ....
}

export function post () {
  // ....
}
```

```js
// index.js

import * as api from './api'

api.get()
```

2. Call `importjs: fix all imports` on index.js

Results:
```js
// index.js

api.get()
```

Tested on:
- Sublime Text 3
- node `v6.6.0`
- importjs `2.1.0`
- macOS sierra

**Comment by trotzig** [comment]
I'm good, thanks for asking!

I've confirmed this being a bug. I haven't quite figured out where in the code the line is being removed yet, but I'm looking at it now. I hope to have a fix out soon. Thanks for taking the time to report it!

**Comment by asfktz** [comment]
Sure, this is the least I can do (:
Thanks, @trotzig

**Comment by asfktz** [comment]
Sure, this is the least I can do (:
Thanks, @trotzig 

I would like to test it on my machine,  how can I do it before a new version is released? 
usually I do `npm install -g import-js`

**Comment by trotzig** [comment]
You can clone the project and run `npm link`. 

```sh
git clone git@github.com:Galooshi/import-js.git
cd import-js

# Install dependencies
npm install

# Transpile files
npm run build 

# Link the binary
npm link
```

When you are done testing and want to go back to the stable version (installed via `npm install -g import-js`), you just run `npm unlink`.

**Comment by trotzig** [comment]
You probably have to restart your editor after making these changes. 

What editor are you using by the way? I realize these instructions won't work in the atom plugin.

**Comment by asfktz** [comment]
I use Sublime Text 3. As much as I'd like to try something new, it's hard to let go after I configured every inch of it 😆

At first glance, looks like it works
I'll test it more thoroughly tomorrow, and let you know if I find anything funny.

**Comment by trotzig** [comment]
@asfktz if you install the latest version now, you can remove the master clone. Just remember to run `npm unlink` before. Thanks for testing things out, I appreciate it!

**Comment by asfktz** [comment]
It's been a few busy days for me lately, Finally manage to find some free time.

Seems like all works as expected regarding the import behavior.
One thing I noticed is that the exclude list is ignored.
I created a separate issue for it: #375
