### ISSUE TITLE
Files listed in the Exclude list are still imported

### ISSUE THREAD

**Issue by asfktz** [Galooshi/import-js#375]
Steps to reproduce:

1. Create 3 files:

```js
// ./ignoreMe.js

export default function () {}
```

```js
// ./importMe.js

export default function () {}
```

```js
// ./index.js

ignoreMe
importMe
```

2. Create `.importjs.js` file and configure it to exclude `./ignoreMe.js` 

```js
// ./.importjs.js

module.exports = {
  excludes: [
    './ignoreMe.js'
  ]
}
```

3. Run `ImportJS: fix all imports` in `index.js`

Results:
```js
// ./index.js

import ignoreMe from './ignoreMe';
import importMe from './importMe';

ignoreMe
importMe
```

Tested on:
- Sublime Text 3
- node `v6.6.0`
- import-js `2.1.3`
- macOS sierra

**Comment by trotzig** [comment]
Can you try restarting your editor in between tries? I have a feeling I took a shortcut here, excluding things only on startup or something. This is still a bug that should get fixed, I'm mostly interested in finding a workaround for you.

**Comment by asfktz** [comment]
Yup, restart did the trick.

As of anything related to the previous issue, I believe you solved it (:
