### ISSUE TITLE
on meteor environement, you can't alias node-modules properly

### ISSUE THREAD

**Issue by macrozone** [Galooshi/import-js#381]
given

```
module.exports = {
  environments: ['meteor', 'node'],
  declarationKeyword: "import",
  aliases: {
    "_": "lodash"
  }
}

```

auto-import _ leads to:

```
import _ from '/lodash';
```

instead of 

```
import _ from 'lodash';
```

**Comment by trotzig** [comment]
Ah, thanks for the report. [Here's where we add that slash](https://github.com/Galooshi/import-js/blob/f41b247dff1a0b6375383eab1f2dfee36fb90d96/lib/environments/meteorEnvironment.js#L340). In case of aliases, `pathToImportedModule` is probably equal to the alias itself, so it doesn't contain a "real" path. 

I'm glad you reported this, as it made me think of a more robust fix. I'll push a PR shortly.
