### ISSUE TITLE
findUndefinedIdentifiers returns anything that's referenced before it's declared.

### ISSUE THREAD

**Issue by dcporter** [Galooshi/import-js#383]
If a file references a variable higher in the file than that variable's declaration — valid JS if the reference is within a function — `findUndefinedIdentifiers` flags it as not locally defined. This can result in bad imports, especially invalid same-file imports like `import { abc } from [this same file which exports abc]`. (The same-file issue is where I ran into it, but it'll add the import if that symbol is exported from anywhere.)

In this minimal example, `abc` will be returned from `findUndefinedIdentifiers` despite being defined (and, since `abc` is an export, it will be added as an import to this same file on `importjs fix`):

```js
function modifyAbc() {
    abc.def = 4;
}

export const abc = {};
```

The root cause is that `visitIdentifierNodes` ([here](https://github.com/Galooshi/import-js/blob/master/lib/visitIdentifierNodes.js#L57)) walks the AST tree once, looking for declarations and references *and comparing them* in the same pass. Solutions include walking the tree twice, or walking it once but compiling two lists (references and declarations) and comparing them at the end.

(Followup: the fix may be more complicated than that. I'm having trouble tracing data through those calls, and scopes are hard.)

**Comment by dcporter** [comment]
I'm able to work around this locally in `Importer#findOneJsModule` by filtering out results whose path matches the `Importer`’s own path, but that's ugly, and I bet that this issue with `visitIdentifierNodes` is causing other subtle bugs elsewhere.

**Comment by trotzig** [comment]
Good catch. I think you are right in that we should fix this in `visitIdentifierNodes`.
