### ISSUE TITLE
importStatementFormatter should get moduleName passed in

### ISSUE THREAD

**Issue by dcporter** [Galooshi/import-js#385]
At the call spot ([here](https://github.com/Galooshi/import-js/blob/master/lib/ImportStatements.js#L201)), the config call args `importStatement` and `pathToCurrentFile` get passed in, but `moduleName` would be super super useful in there, and it appears to be available at that location on `importStatement.path`.

**Comment by trotzig** [comment]
Do you have a more concrete use-case? Would a combination of `moduleNameFormatter` and `importStatementFormatter` work?

**Comment by dcporter** [comment]
I'm building custom import statements for certain modules, and having to extract the module from the `importStatement` in order to switch on it is cumbersome and seems unnecessary. The module names are being formatted correctly, I don't think that `moduleNameFormatter` is going to help (except in awful hacky ways like wrapping it in a unique string to make it easier to extract 😳). Locally, I've got `importStatement.path` piped in through the extant `moduleName` config function arg, and it appears to be working great.

Specifically, I'm trying to use `aliases` and `importStatementFormatter` to implement #353 on my own — for *certain* dependencies, I want to do (e.g.) `import * as mobx from 'mobx'`; by default, `aliases` instead generates `import mobx from 'mobx'`, so I need to figure out which module I'm looking at in order to know when to modify it.

(Separately, I would be interested to hear your thoughts on how you would implement #353.)

**Comment by trotzig** [comment]
I added my thoughts on that issue. 

As for passing in the `moduleName`, that sounds like a good idea.

**Comment by dcporter** [comment]
Fixed in 96c22c5.
