### ISSUE TITLE
importjs and importjsd cannot run

### ISSUE THREAD

**Issue by deltaskelta** [Galooshi/import-js#396]
OSSierra 10.12.4
MacVim 8.0.525

I installed importjs and the vim plugin, but it wasn't working. When I called commands it said `importjsd` not running. 

I tried to run `importjsd` from the commadn line and I got the following error.

```
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen(/usr/local/lib/node_modules/import-js/node_modules/sqlite3/lib/binding/node-v51-darwin-x64/node_sqlite3.node, 1): no suitable image found.  Did find:
	/usr/local/lib/node_modules/import-js/node_modules/sqlite3/lib/binding/node-v51-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1609728 which is past end of file 777216
	/usr/local/lib/node_modules/import-js/node_modules/sqlite3/lib/binding/node-v51-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1609728 which is past end of file 777216
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/import-js/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
``` 

I tried to run `--help` and `--version` on both `importjs` and `importjsd` and got the same error, not sure if those are even valid commands or not...

**Comment by trotzig** [comment]
Hi @deltaskelta, and thanks for reporting your issue. Sorry for the delayed response, I've been afk for a while. 

I haven't seen this error before, but it looks like an issue with sqlite trying to open a file. We use sqlite for the exports cache, and the default location of that file is in the OS tmp folder. You can check what import-js uses by running `importjs cachepath`. 

It might be some permission thing. You could try overriding the path to the cache file with the `cacheLocation` config option. This option is undocumented so far, I've mostly used it for testing things. Try this: 

```js
// .importjs.js
module.exports = {
  cacheLocation: 'import-js-cache.db',
};
```

(you might have to use an absolute path, I'm not 100% sure).

**Comment by trotzig** [comment]
I just realized the error stack had more info when I scrolled right. Another thing you could try is to run `npm rebuild sqlite3`, as it seems the sqlite installation might have ended up in the wrong state.

**Comment by deltaskelta** [comment]
just earlier today before I saw this I tried to uninstall and reinstall `import-js` and it seemed to have fixed the problem...Not sure what went wrong, I thought I tried that before, but maybe I was wrong. Thanks for the reply!

**Comment by trotzig** [comment]
Glad you got it sorted out. Thanks for cycling back and closing the issue! 👍

**Comment by trotzig** [comment]
Let me know if you notice any other issues. I haven't tried out import-js much in MacVim (I'm a regular vim user myself).
