### ISSUE TITLE
A secondary package.json file messes things up

### ISSUE THREAD

**Issue by rndmerle** [Galooshi/import-js#410]
Took me a good while to spot the cause.

On a react-native project, if you want absolute imports, you've to put an other package.json into app/ _(or whatever is your sources folder)_ containing `{ "name": "app" }`

The simple fact to have that **additional package.json** severely hinders import-js functionnalities, at least :
- .importjs.js **config file is completely ignored**
~~- on Windows, import paths get **backslashes** instead of slashes~~ EDIT: actually it was just due to useRelativePaths getting back to true.

**Steps to reproduce :**
- `echo "{}" > ./lib/package.json`
- Test importjs _(tested only the atom add-on actually)_ on a file under ./lib or further down. Aliases won't work for instance.

If you need further testing let me know.

**Comment by trotzig** [comment]
> On a react-native project, if you want absolute imports, you've to put an other package.json into app/ (or whatever is your sources folder) containing { "name": "app" }

I think a better solution would be to add a `moduleNameFormatter` function to .importjs.js, where the "app/" part is stripped out. See https://github.com/Galooshi/import-js#modulenameformatter

**Comment by trotzig** [comment]
Something like 

```js
moduleNameFormatter: ({ moduleName }) => {
  moduleName.replace(/^app\//, '');
}
```

**Comment by rndmerle** [comment]
Actually, now I understand how it finds the project's root, I'd have to put the .importjs.js in the app/ folder (next to the extra package.json).

The `moduleNameFormatter `would then have to actually add app/ in front of the import.
