### ISSUE TITLE
Named exports detection foiled by top-level conditional

### ISSUE THREAD

**Issue by lencioni** [Galooshi/import-js#411]
Some packages, like airbnb-prop-types, will have different builds for production vs development, in order to minimize bundle size. In this case, the entry point looks something like this:

```js
module.exports = process.env.NODE_ENV === 'production'
  ? require('./build/mocks')
  : require('./build');
```

https://unpkg.com/airbnb-prop-types@2.5.4

This ends up breaking the named exports detection for this package. I'm not entirely sure what the best solution is here, but in this case it would work if import-js followed either path, since they should both be exporting the same set of things. Perhaps we could add some special cases for `process.env.NODE_ENV` checks and follow the production path?

cc @dabbott

**Comment by trotzig** [comment]
I've got a solution coming up that just picks the first alternative (the `consequent` in the AST). At this point, I don't think we need to special-case `process.env.NODE_ENV`.
