### ISSUE TITLE
Upgrading to full-text on existing project crashes

### ISSUE THREAD

**Issue by dcporter** [Galooshi/import-js#416]
Any existing project that takes the new full-text search update (#414) crashes because table `exports_full_text_search_index` was never created — the database looked initialized, so the whole setup phase was skipped. That makes this a breaking change, though I assume/hope it's pretty easy to check for that table specifically?

**Comment by trotzig** [comment]
Ah, great catch! I'll just bump the cache db filename before the release, that will "invalidate" (abandon) the old cache and create a new.
