### ISSUE TITLE
Default parameters shouldn't import

### ISSUE THREAD

**Issue by dabbott** [Galooshi/import-js#418]
Currently when using an ES2015 method definition with a default parameter, e.g:

```js
const obj = {
  method(foo = 1) {}
}
```

`foo` will be imported. This only happens when there's a default parameter. It also happens for setters (though probably this would never happen in real code):

```js
const obj = {
  set value(foo = 1) {}
}
```

**Comment by lencioni** [comment]
Good find! I'm guessing this is a bug in `findUndefinedIdentifiers`. Would you be interested in opening a PR? (Even a PR with just a failing test would be awesome!)

**Comment by dabbott** [comment]
Fixed! It turned out that default parameters in general don't get imported.
