### ISSUE TITLE
Including import statement in unresolved imports resolution dialog

### ISSUE THREAD

**Issue by dabbott** [Galooshi/import-js#422]
Currently the unresolved imports dialog can be a little confusing. Showing file paths tends to create a lot of noise. We could potentially leave off the file path, but there isn't quite enough information to make a good choice from just the `displayName`

E.g:
![screen shot 2017-06-09 at 11 28 33 am](https://user-images.githubusercontent.com/1198882/26989186-fe290f28-4d06-11e7-9bfe-9f3234e4dff8.png)

It would be easier to make the right choice if we showed the actual import statement. The choices are pretty clear when displayed like this:

![screen shot 2017-06-09 at 11 15 24 am](https://user-images.githubusercontent.com/1198882/26989237-3367dfc0-4d07-11e7-8d54-e7c585fa1d92.png)

In cases where two import statements look exactly the same, the full path will still need to be shown -- but it can probably be left to the editor plugin to figure out the best way to display things.

**Comment by lencioni** [comment]
Closed by #423
