### ISSUE TITLE
Excludes should allow excluding specific node_modules

### ISSUE THREAD

**Issue by dabbott** [Galooshi/import-js#424]
We have some node_modules that I'd like to hide from application developers unless imported manually.

![screen shot 2017-06-09 at 2 32 33 pm](https://user-images.githubusercontent.com/1198882/26995271-8a393286-4d20-11e7-8421-c36c5deac83e.png)

99% of the time, Text should come from react-native. If a developer wants the one from react-native-svg or react-native-mock, that should be imported manually. So I'd like to be able to use `excludes` for node_modules, which right now doesn't seem to work.

E.g.

```js
{
  excludes: ['./node_modules/react-native-svg'],
}
```

or something like that. Maybe there's a better, more generic way of excluding things that would also allow excluding specific named exports from a module (https://github.com/Galooshi/import-js/issues/419)

**Comment by trotzig** [comment]
That's unfortunate. It looks like we could make a quick-fix and just move this section a bit higher: 
https://github.com/Galooshi/import-js/blob/8bbf6b5827cedb29136375d7f99abfe9df9fd3f5/lib/findJsModulesFor.js#L64

It's also worth noting that [`importDevDependencies`](https://github.com/Galooshi/import-js#importdevdependencies) could play a role here. It looks to me like `react-native-mock` could be a dev dependency? In such case, you could conditionally allow importing dev dependencies by implementing `importDevDependencies` as a function.

**Comment by dabbott** [comment]
I like the quick fix. https://github.com/Galooshi/import-js/pull/427

`react-native-mock` should be a dependency, but it can't be because... reasons :P

**Comment by lencioni** [comment]
Since we have a quick fix merged, I'm going to close this. Feel free to open a new issue if you find that we need to improve this in any way.
