### ISSUE TITLE
Supporting Flow's type imports

### ISSUE THREAD

**Issue by rndmerle** [Galooshi/import-js#426]
Has it been already discussed ?

`export type Color = string;`

should be imported as
`import type { Color } from './Types.js';`

**Comment by trotzig** [comment]
I can't recall this being discussed previously. This would be a good addition.

**Comment by lencioni** [comment]
Agreed! This definitely makes sense. @rndmerle would you be interested in submitting a PR that adds this functionality? `findExports` might be a good place to start.

**Comment by rndmerle** [comment]
I'll try to have a look at it :)

**Comment by rndmerle** [comment]
Getting exports done was quite easy, thanks to the parser.
But handling imports is another story :p

I guess we can't mix named exports and type exports, so we'd have to store them in their own array.

And we'd have to take into account the two different kinds of import statement:
`import type { Bar, Baz } from './Types'`
and 
`import Module, { foo, type Bar } from './Module'`

_for this kind of exports :_
```export type Bar = string;
export type Baz = number;
export const foo = '';
export default function () {}```

**Comment by rndmerle** [comment]
I've been a bit out of time lately but today I've been able to pull out a solid coding session and I've made some good progress imo. Exports and ImportStatements are fine, I need to do more tests.

The SQL schema has been modified (a new isType column) and I was wondering how can the transition/migration be smoothly handled on an existing project.

**Comment by trotzig** [comment]
Nice! For the schema change, I've just been bumping a version number for the location of the file. Change the `v3` to `v4` here:
https://github.com/Galooshi/import-js/blob/f8d6ae520f120ca9139d4e2665f660ef63d07c36/lib/Configuration.js#L42

At some point, we might have to become smarter about migrations instead of throwing the old storage out. But right now I think this is good enough.

**Comment by rndmerle** [comment]
It works nicely, hopefully. Gonna push the PR.

![type imports](https://user-images.githubusercontent.com/79888/27404912-ff3b8e9a-56cf-11e7-8178-480cd1fbb458.gif)

**Comment by macrozone** [comment]
@rndmerle any update on this? would love to have that <3

**Comment by rndmerle** [comment]
It should be in the 2.7.0 version released 2 days ago.
However, it's probably not yet propagated to the editor add-on you're maybe using.

**Comment by macrozone** [comment]
already added an issue to the atom version, thx
