### ISSUE TITLE
Would be nice to add babylon parser plugin array to configuration.

### ISSUE THREAD

**Issue by paradoxxxzero** [Galooshi/import-js#428]
[This array](https://github.com/Galooshi/import-js/blob/master/lib/parse.js#L8-L15) is hard coded and as-is it makes import-js crash when dynamic imports are used. Adding the `dynamicImport` plugin to the array fixed it for me but not everyone would want that I assume so it could be great to make it customizable.

Thanks for this great project.

**Comment by lencioni** [comment]
[Dynamic imports are a stage 3 proposal](https://github.com/tc39/proposal-dynamic-import), which means that the spec is complete and browsers should start implementing. I think this is the point where we would want to include something like this for everyone.

With that said, I also see value in exposing this as configuration for folks who want to use more experimental features. I'll add the dynamicImport plugin now and would be happy to review a PR that makes this configurable. @trotzig what do you think?

**Comment by lencioni** [comment]
> I also see value in exposing this as configuration for folks who want to use more experimental features

Thinking about this a bit more, it seems that we should keep it simple for now and wait to see if anyone needs to be able to configure the babylon plugins before adding that feature. Please re-open if you'd still like to be able to do this now that dynamicImport is in the list for everyone.

**Comment by paradoxxxzero** [comment]
Fair enough, thanks a lot!

**Comment by lencioni** [comment]
No problem! Also, I just published 2.5.0 with this fix. Thanks for reporting!
