### ISSUE TITLE
Export alias is considered as an undefined variable

### ISSUE THREAD

**Issue by rndmerle** [Galooshi/import-js#442]
Sample file containing only :
```
const test = {};
export { test as react };
```
I trigger a fix-import on that and it imports the react library:
```
import react from 'react';

const test = {};
export { test as react };
```

Same issue with my own modules indeed.

**Comment by trotzig** [comment]
Ah, good catch!

I won't be able to get to this until after a bit of time off, but anyone should feel free to submit a PR fixing this. Here's a good commit to look at for inspiration on what needs to be done, and how to test the change: 
https://github.com/Galooshi/import-js/commit/02d183d69858487ee196d734db54c04cb6dd2b23

**Comment by trotzig** [comment]
I found some time 😃
