### ISSUE TITLE
Relative/Absolute hybrid import

### ISSUE THREAD

**Issue by rndmerle** [Galooshi/import-js#446]
_Before considering working on a PR here is a potential improvement, but not sure if it's appropriate._

On my last project, I've been switching to absolute importing.
While it's nice for importing stuff **from sibling or parent folders**, it seems wrong when it's **modules from the same folder, or children** ones.

Would a hybrid system seems relevant?

**Comment by trotzig** [comment]
This should be possible with a custom `moduleNameFormatter` implementation. Something like

```js
// .importjs.js
module.exports = {
  moduleNameFormatter: ({ pathToImportedModule, pathToCurrentFile, moduleName }) => {
    if (inSameFolder(pathToImportedModule, pathToCurrentFile)) {
      return removeAbsolutePath(pathToImportedModule);
    }
    return moduleName; // Fall back to default behavior
  }
}
```

This is from memory, not tested in the wild. Of course, you'd have to implement `inSameFolder` and `removeAbsolutePath` for this to actually do anything.

**Comment by rndmerle** [comment]
Thanks for the tip.

However, I was more asking if it's a feature you want added to the project.
We'd need to add a new configuration parameter of some sort tho.

With such files:
```
/A/foo/index.js
/A/foo/foo.js
/A/foo/bar/bar.js
/A/baz.js
/B/quux/qux.js
```
You'd get:
```
// index.js
import Foo from './foo';
import Bar from './bar/bar';
import Baz from 'A/baz';
import Qux from 'B/quux/qux';
```
It seemed more adequate then either:
```
// index.js
import Foo from './foo';
import Bar from './bar/bar';
import Baz from '../baz';
import Qux from '../../B/quux/qux';
```
or
```
// index.js
import Foo from 'A/foo/foo';
import Bar from 'A/foo/bar/bar';
import Baz from 'A/baz';
import Qux from 'B/quux/qux';
```

**Comment by trotzig** [comment]
We already have a lot of configuration options, and I'm hesitant to adding a new one for this purpose when existing options already allow you to accomplish the desired output.

**Comment by rndmerle** [comment]
Yea totally understandable. No problem.
