### ISSUE TITLE
PropTypes react 15.5+ wrong import

### ISSUE THREAD

**Issue by cj** [Galooshi/import-js#447]
Currently `PropTypes.object` is producing `import { PropTypes } from 'react'`,  from react 15.5 onwards this should be `import PropTypes from 'prop-types'`.  Is there a way to correct this using the `.import.js` config file?

**Comment by rndmerle** [comment]
It should ask you which of the two you want to import.
Are you sure `prop-types` is installed in normal dependencies? or if `importDevDependencies` is true ?

As for forcing that with some configuration, it's quite dirty and not really recommanded:
```
namedExports: {
    'prop-types': ['PropTypes'],
},
importStatementFormatter({ importStatement }) {
    return importStatement.replace(/{ PropTypes }/, 'PropTypes');
},
```

**Comment by deltaskelta** [comment]
@rndmerle what do you mean by "installed in normal dependencies?" does that mean installed with `--save-dev` or just bare npm installed?

I use `create-react-app` and I was never asked which one I would like to import and I am getting the same error.

**Comment by rndmerle** [comment]
I just tested it and it's working
```
$ npm i -g create-react-app
$ create-react-app testing
$ cd testing
$ npm i --save prop-types
```
Using atom with import-js package I get two options:

![image](https://user-images.githubusercontent.com/79888/28392004-6fd92178-6ce0-11e7-9ade-ecfbd6afe799.png)

**Comment by deltaskelta** [comment]
I just did the same thing with vim and wen I added PropTypes to `App.js` it imported `PropTypes` from react without asking…

```
import './App.css';

import React, { Component, PropTypes } from 'react';

import logo from './logo.svg';

class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h2>Welcome to React</h2>
        </div>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
    );
  }
}

App.proptypes = {
  test: PropTypes.string
}

export default App;
```

-------------------------------
Jeff Willette
jrwillette88@gmail.com

**Comment by deltaskelta** [comment]
If I were to have accidentally chosen the wrong port without knowing, how could I undo all knowledge if my previous choice so that it would ask me which one I would like to use again?

**Comment by trotzig** [comment]
@deltaskelta can you check the package.json file in your project -- does it list `prop-types` as a dependency?

If you want to change an existing import, you can either use the "import word under cursor" command (which will overwrite the import for the specific word/variable), or just delete the import statement at the top of the file and re-import.

**Comment by deltaskelta** [comment]
yes I eventually found out that if I manually deleted them all from the project, it would ask me again which ones I should import. 

Prop-types is listed as a dependency now, but I am not sure what the state was when I wrote this. 

Thanks for the reply, @cj can you close the issue if your question has been answered?

**Comment by lencioni** [comment]
This seems to have been resolved. Please feel free to re-open!
