### ISSUE TITLE
sortImports configuration option is failing in the current release

### ISSUE THREAD

**Issue by igncp** [Galooshi/import-js#452]
Hi,

First of all kudos for the library, this functionality is very helpful and appreciated.

Just wanted to comment that the current release doesn't contain the `sortImports` option in the `KNOWN_CONFIGURATION_OPTIONS` variable under `lib/Configuration.js`. It was added a few days later, after the release, so installing the package and adding this option will display an `"Unknown configuration"` error.

Currently planning to use this project, but we have a custom eslint rule to sort imports in another way, so it would be nice if we can disable the sorting. I know it is possible to install npm packages using the github repo, but nevertheless it would be nice to have this fix in a versioned release. Thanks again for the repo 👏

**Comment by trotzig** [comment]
Ah, good catch. I forgot about that getting merged after the release. I'll cut a new one during the day (after a few meetings).

**Comment by trotzig** [comment]
I just pushed 2.7.0 with this change

**Comment by igncp** [comment]
Thanks for the quick response
