### ISSUE TITLE
The library doesn't find all modules

### ISSUE THREAD

**Issue by entropitor** [Galooshi/import-js#453]
I have some files that import-js just doesn't find. For example a file called `colors` and has some consts in them together with an `export default {...}`, i have a very similair file called `dimensions` that import-js *does* find.

Any idea what might go wrong?

**Comment by trotzig** [comment]
I can't say much based on that information, but one thing you can do is to add a `logLevel: 'debug'` to your `.importjs.js` config, then tail the log file to check if something fails when parsing that file. 

Tailing the log: 

```bash
tail -f $(importjs logpath)
```

You might have to delete the current cache to get more useful things logged: 

```
rm $(importjs cachepath)
```

The cache file will start getting populated as soon as you import something from your editor. And that's when you'll see logs coming in as well.

**Comment by entropitor** [comment]
When I delete the cache it works for a while, then it starts forgetting to analyse certain files again. I also have to restart vim after deleting the cache before it works again

**Comment by trotzig** [comment]
Yeah, having to restart is expected. The daemon process holds on to a reference to the old file, so it won't recover. I believe this is okay since removing the cache isn't a common thing. I should have told you about it though, glad you figured it out.

Does the log give you anything useful? 

Can you share a little about your project? Is it a react project, plain js, typescript, flowscript or any combination? Can you also share the contents of the `colors` file? I want to understand if there's anything there that's causing confusion to the indexing process.

**Comment by entropitor** [comment]
It's a react-native project with flowtype, I just saw a lot of things passing in the logs. I think it's fixed now, but it might be useful to have the "remove the cache and restart your editor" to the docs under a troubleshooting section.

Thanks for your help though! 😄

**Comment by entropitor** [comment]
Now I have the problem again and I get errors like:

`failed to resolve "dotenv-cli" relative to ...`, however, that package is there and not even required in the file so I'm not even sure why it complains

I also get errors related to flow-type where it doesn't recognize the syntax of type definitions (e.g. the `export` in this line: https://github.com/flowtype/flow-typed/blob/master/definitions/npm/node-fetch_v1.x.x/flow_v0.44.x-/node-fetch_v1.x.x.js#L2)

**Comment by trotzig** [comment]
Sorry to hear that things aren't stable. 

> failed to resolve "dotenv-cli" relative to ..., however, that package is there and not even required in the file so I'm not even sure why it complains

Is this showing up in the log file (`importjs logpath`) or inside your editor? 

> I also get errors related to flow-type where it doesn't recognize the syntax of type definitions

Do you think you could reproduce this in a test case added to https://github.com/Galooshi/import-js/blob/master/lib/__tests__/findExports-test.js ? Once we have that, it's easier to fix the bug.

**Comment by entropitor** [comment]
Both errors are out of the logpath

The last one gives:
```
1505742581426 ERROR PID:1894 Failed to parse ./flow-typed/npm/node-fetch_v1.x.x.js: Unexpected token (5:17)
SyntaxError: Unexpected token (5:17)
    at Parser.pp$5.raise (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$8.flowParseDeclareExportDeclaration (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:5111:14)
    at Parser.pp$8.flowParseDeclare (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:5095:17)
    at Parser.pp$8.flowParseDeclareModule (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:5146:24)
    at Parser.pp$8.flowParseDeclare (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:5086:19)
    at Parser.parseExpressionStatement (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:5921:25)
    at Parser.pp$1.parseStatement (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:1911:17)
    at Parser.parseStatement (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseBlockBody (/usr/local/lib/node_modules/import-js/node_modules/babylon/lib/index.js:2268:21)
```

I'm guessing some babel transform isn't working :/

**Comment by lencioni** [comment]
Ah that's really helpful information. ImportJS uses babylon internally to parse code, so it needs to be configured to be able to understand all of the syntax you use. We had a similar issue earlier with dynamic imports (https://github.com/Galooshi/import-js/issues/428).

It would be really helpful if you could help us pinpoint the bit of syntax that ImportJS is choking on.

**Comment by lencioni** [comment]
Ah looking back at your earlier comment, I see that it might be the flow typed definitions.

Do you think you could open up a PR with a failing test similar to the one that I added here? https://github.com/Galooshi/import-js/pull/429/files#diff-78710dc05b6a19a1931604fbb6698a3aR30

**Comment by entropitor** [comment]
I'm not on my pc where I have this problem, but I think something like this will fail:
```js
it('knows about flow-type declare class exports', () => {
  expect(() => parse(
    `
    declare export class Request {
       constructor(test: string): this
    }
    `,
)).not.toThrowError();
```

**Comment by entropitor** [comment]
@lencioni I've added the failing test. (Notice that if you remove the export, it works just fine)

**Comment by lencioni** [comment]
@entropitor thanks for the PR, it was very helpful. As far as I can tell, this syntax is not supported by the latest release of babylon, but I tried it out with 7.0.0-beta.20 and it seems to work fine.

I think for now the best plan is to wait for babylon v7 to be released and then we can update to that version and this should just work.

If you want to verify, you can run:

```sh
npm i babylon@7.0.0-beta.20
npm test
```
