### ISSUE TITLE
Goto ignores extension for default export which does not match the filename

### ISSUE THREAD

**Issue by madox2** [Galooshi/import-js#455]
Given the file `./this-is-something-else.js` and code:
```javascript
import someWeirdName from './this-is-something-else';
```
It is navigated to `./this-is-something-else` (which does not exists) instead of navigating to file with `.js` extension. This might be related to #177

**Comment by trotzig** [comment]
I think this is a duplicate, but thanks for reporting anyway. The `goto` command needs a bit of work as it looks like it's ignoring current imports when resolving the module. Any help here is much appreciated. It looks like [this line](https://github.com/Galooshi/import-js/blob/f7a9a0a938cdf2780aa9c9d38935ddf8ea5ae7a1/lib/Importer.js#L132) is to blame. It might be enough to make a call to `this.findCurrentImports();` above and look at the current imports for one that's matching the variable name. If we find one, pass it through `requireRelative.resolve` (similar to what we do here: https://github.com/Galooshi/import-js/blob/5d3a409100b20bfa3a205ab9939d686ce3f671c1/lib/findExports.js#L123).

**Comment by madox2** [comment]
@trotzig I don't think it is duplicate since original issue was resolved. However it is not possible to resolve module extensions in such cases.

**Comment by trotzig** [comment]
Ah, sorry. I didn't look at all the comments there. It looks like I closed it with a commit that took us closer to a proper fix, but it left some cases unsolved (like the one you're describing). Let's continue in this issue.

**Comment by hontas** [comment]
I took a quick look and it's hard to know where the fix should go when not aware of the architecture + I couldn't get the tests to run because I don't know flow - which gave me an error I didn't understand how to resolve.

However...

I ended up adding 
```js
if (path.extname(filePath) === '') {
  try {
    fs.accessSync(filePath);
  } catch (e) {
    const basename = path.basename(filePath);
    const dirname = path.dirname(filePath);
    const files = fs.readdirSync(dirname);
    const match = files
      .find((file: string): boolean =>
        basename === path.basename(file, path.extname(file)));

    if (match) {
      filePath = `${dirname}/${match}`;
    }
  }
}
```
in `Importer.js` just after
```js
let filePath = jsModule.resolvedFilePath(
  this.pathToCurrentFile,
  this.workingDirectory,
);
```

And I could then use `goto` in Sublime for this scenario: `import classes from '../../../common/utils/classes';`

Maybe it's a naive solution, maybe it should go in `JsModule.js` - but it is nice when it works ;)
