### ISSUE TITLE
No JS module to import for 'React'

### ISSUE THREAD

**Issue by rivertam** [Galooshi/import-js#461]
Hi there. I'm trying to use import-js because the functionality seems incredible and it seems to work for a lot of people.

However, it doesn't seem to be working for me even in the slightest.

I made an extremely basic repo to test this out. All it has is a `package.json` and an `index.js`. I ran `npm init && npm install react`, and `index.js` just has the following in it:

```js
class Hi extends React.Component {

}
```

Essentially, I think this is pretty much the easiest possible usecase, yet import-js gives back "No JS module to import for 'React'" in vim when I use `:ImportJSWord`. When I run `importjs fix index.js` on the command line, I get:

`{"messages":[],"fileContent":"class Hi extends React.Component {\n\n}\n","unresolvedImports":{}}`

I'm pretty confused. I'm usually pretty bad at installing things as I ignore configuration options and that kind of thing, but I've been troubleshooting this for a while and can't figure it out. I tried adding a blank configuration file and adding node as an environment. I tried installing Watchman. I tried updating node and npm.

Any ideas?

Thanks!

**Comment by lencioni** [comment]
Can you share your repo?

I'm guessing that react isn't listed in your package.json dependencies.

**Comment by rivertam** [comment]
Ah, yes, adding it to my package.json dependencies did fix the issue.

I think I understand why this is happening in my non-minimal case, then. I'm using https://github.com/chentsulin/electron-react-boilerplate, and that has two different `package.json`s... the main one is in the higher level directory, so that would probably explain that.

It looks like there is currently no way to specify in the config or elsewhere where the project root is. Would you be against me making a PR to add this to the config? Or am I mistaken and there is actually a way to specify this?

I appreciate your timely response!
