### ISSUE TITLE
Global configuration

### ISSUE THREAD

**Issue by TrySound** [Galooshi/import-js#465]
All my projects looks the same, so I'd like to set configuration globally, maybe in user directory, and do not add `.importjs.js` to each project since it's only my environment option.

**Comment by trotzig** [comment]
This sounds like a good idea, and I'd be open to a PR adding support for it. In the meantime, the best thing you can do is to drop something like this in your .importjs.js files:

```js
module.exports = require('/Users/foobar/.importjs.js');
```
