### ISSUE TITLE
Logpath: No such file

### ISSUE THREAD

**Issue by peterp** [Galooshi/import-js#470]
```
cat $(importjs logpath)
cat: /var/folders/jg/tczxx4hs5_32s1z2mw02b94r0000gn/T/importjs.log: No such file or directory
```

OS X with importjs 2.8.0

**Comment by trotzig** [comment]
This might be because nothing has been written yet. Did you expect anything to be there? (was there anything broken that led you there?)

**Comment by trotzig** [comment]
You could change the logLevel in config to see if anything changes: 

```js
// .importjs.js
module.exports = {
  logLevel: 'debug',
};
```

**Comment by peterp** [comment]
I get an error in Atom: "No JS Module found for "PropTypes"", so I wanted to figure out why and the log seemed like the most logical place, my configuration is set to debug.

**Comment by peterp** [comment]
I realise now that `cmd+shift+k` opens the file for the module, and this is what was not functioning.

**Comment by trotzig** [comment]
Ah, I see. If you have `logLevel: 'debug'`, restart atom, then try importing something, I believe you should get enough things logged to help you debug why proptypes can't be found. If you can't find anything useful there, the first thing to check is that `prop-types` is listed as a dependency in package.json.

**Comment by peterp** [comment]
Thanks!
