### ISSUE TITLE
emptyLineBetweenGroups not working

### ISSUE THREAD

**Issue by jbharat** [Galooshi/import-js#478]
`emptyLineBetweenGroups` doesn't seem to work in 2.9.0. I have the following configuration in my .importjs.js file in the project root.

```
module.exports = {
  environments: ['node'],
  ignorePackagePrefixes: ['lodash.'],
  groupImports: true,
  sortImport: false,
  emptyLineBetweenGroups: false,
  declarationKeyword: 'import',
  logLevel: 'debug',
  excludes: ['./build/**', 'node_modules'],
};
```
but the output is 
```
import './App.css';

import React from 'react';

import Stories from './components/Stories';
```
Also is it possible to provide sorting functionality as per groups. Eslint shows error when using airbnb style guide. It expects absolute imports at the beginning and relative later as shown below
```
import React from 'react';
import { compose } from 'lodash/fp';
import { Stories } from '../components;
import { AuthHoc } from '../libs';
```

**Comment by trotzig** [comment]
The first part is because the new config option hasn’t been released yet (it was merged yesterday I believe). I’m awaiting a few other changes before making a release, so stay tight.

@lencioni, can you perhaps respond to the second question about airbnb eslint?

**Comment by jbharat** [comment]
as per the docs `--fix` option to eslint should fix it. I will give it a try. Thanks
