### ISSUE TITLE
Object destruction with assigning to new names

### ISSUE THREAD

**Issue by kahless** [Galooshi/import-js#485]
If my code contains an object destruction with assigning to new constant name:

    const { id: langForeignID } = findByName(LANG_FOREIGN, en.langs);
    console.log(langForeignID);

Then import-js does not recognize this syntax and tries to import the already defined `langForeignID` constant:

    import { langForeignID } from "P/src/comp/learn/sel-domains";

This destruction syntax is a part of ES2015:
https://www.ecma-international.org/ecma-262/6.0/#sec-destructuring-assignment
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

**Comment by trotzig** [comment]
Ah, sounds like you caught a bug in [findUndefinedIdentifiers.js](https://github.com/Galooshi/import-js/blob/master/lib/findUndefinedIdentifiers.js). Basically, it needs to pass this test: 

```js

it('recognizes destructured assignment to a new name', () => {
  expect(findUndefinedIdentifiers(parse(`
    import Foo from 'foo';
    const { bar: scar } = Foo;
    scar();
  `))).toEqual(new Set([]));
});
```

I have limited time right now so any help here would be appreciated!

**Comment by kahless** [comment]
I will try. Not sure if I succeed. But I will report the results.
