### ISSUE TITLE
Import-Js Generating multiple lines for the same file

### ISSUE THREAD

**Issue by Rybadour** [Galooshi/import-js#499]
When I import something from another file that isn't the default export it will create multiple import statements.

Ex. 

```
import {x} from './foo';
import {y} from './foo';
import {z} from './foo';
```

When it should be just one line:

```
import {x, y, z} from './foo';
```

I'm using it through vim-import-js, but I don't think that would change anything, right?

**Comment by trotzig** [comment]
If I’m not mistaken, import-js will always adf spaces inside the curlies. Are you sure this is import-js?

**Comment by Rybadour** [comment]
Yes this is import-js, unless something else shares exactly the same Config structure.

It's just that I constructed an example manually.

**Comment by trotzig** [comment]
Ah, I see. I haven’t seen this before. They should get combined. Can you turn on more logging (`logLevel: ’debug’` in .importjs.js) and then see if you spot anything weird when importing? The logfile is written to a tmp file, run `importjs logpath` to get a path to thag file.

**Comment by Rybadour** [comment]
Nothing shows up. I see lots of unrelated messages in there. And besides this issue I have no problems with import-js. It does create the import and uses my config correctly.

**Comment by Rybadour** [comment]
Oops nevermind, my file had invalid syntax. So I guess the default behaviour is just to prepend the import line to the top of the file?

Okay I'll keep that in mind for later.

Everything is working now that my file has no syntax errors.
