### ISSUE TITLE
add config option to ignore import by keyword

### ISSUE THREAD

**Issue by deltaskelta** [Galooshi/import-js#500]
My use case is that I am using [gatsbyjs](https://github.com/gatsbyjs/gatsby) which runs graphql queries at runtime. It uses a graphql tag.

I am also using [react-apollo](https://github.com/apollographql/react-apollo) which exports a graphql function. I run importjs in vim and it automatically imports the graphql from react-apollo (because gatsby's isn't mean to be imported) even though I do not want that one.

Is there currently a way to ignore the graphql keyword entirely?

**Comment by coagmano** [comment]
If you add it to `globals` in your config it will ignore the keyword
https://github.com/Galooshi/import-js#globals

**Comment by deltaskelta** [comment]
Oh I see, I must have skimmed over that word in the config since it doesn't seem like it does that :)
