### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by vjsingh** [Galooshi/import-js#503]
Does this project work with typescript files (.ts, .tsx)?

I tried two identical files, one '.js' and one '.ts' and import-js is not finding the export in the typescript file. I tried to debug but having trouble reading the long log file.

**Comment by trotzig** [comment]
At this point import-js won't process .ts files. I'm not using typescript myself, so I'm relying on an outside contribution to add support.

**Comment by lencioni** [comment]
I think Babel 7 will have built in TS support. Under the hood, import-js uses Babylon. It is possible that we just need to update to a newer (possibly still in beta) version and maybe flip on some options.

**Comment by williamboman** [comment]
I've added TS support in my fork (https://github.com/williamboman/import-ts). See the diff [here](https://github.com/Galooshi/import-js/compare/master...williamboman:master). Seems to work fine locally, feel free to use this as a base for a proper PR to this repo.

**Comment by lencioni** [comment]
There's also #505 which updates this project to Babel 7. 

@williamboman your fork looks pretty good to me. Do you think it is possible to add support for TS without removing support for Flow?

**Comment by williamboman** [comment]
> @williamboman your fork looks pretty good to me. Do you think it is possible to add support for TS without removing support for Flow?

Yeah it should be fine. However, when parsing a file you cannot have both `typescript` and `flow` plugins enabled. I'm thinking this could be accomplished by always defaulting to `flow` and substituting it with `typescript` if `/\.tsx?$/.test(fileName)`.

**Comment by lencioni** [comment]
That makes sense to me!

**Comment by lencioni** [comment]
@williamboman would you be willing to incorporate anything useful from #505, make it work with Flow as described above and open a PR? I'd love to have out of the box support for TS here!

**Comment by williamboman** [comment]
I'll take a look soon<sup><sup>:tm:</sup></sup>!

**Comment by trotzig** [comment]
Closing this issue as we now have typescript support. Since 3.1.0.
