### ISSUE TITLE
import styled from 'styled-components'; ? 

### ISSUE THREAD

**Issue by zirho** [Galooshi/import-js#511]
Hi there,

I was trying to figure out how I can do 
`import styled from 'styled-components';`
I tried many ways and could not figure it out.
```
  aliases: {
    styled: 'styled-components',
  },
```
Please help.

Thanks!

**Comment by rivertam** [comment]
You have to use `styled: 'node_modules/styled-components'`. The docs could definitely be clearer on this, as I wrestled with this myself a couple weeks ago.

**Comment by zirho** [comment]
thank you!
