### ISSUE TITLE
Object rest falsely not registering as defined

### ISSUE THREAD

**Issue by rivertam** [Galooshi/import-js#512]
Test case:

```js
// ok.js

export function test({ ...props }) {
  return console.log(props);
}
```

```js
// .importjs.js

const _ = require('lodash/fp');

module.exports = {
  namedExports: {
    'lodash/fp': Object.keys(_),
  },
};
```

on running `importjs fix ok.js`, the following output appears:

```js
{"messages":["Imported { props } from 'lodash/fp'"],"fileContent":"import { props } from 'lodash/fp';\n\nexport function test({ ...props }) {\n  return console.log(props);\n}\n","unresolvedImports":{}}
```

I've been looking through the code and I don't really understand it but I think the issue is probably in [`visitIdentifierNodes`](https://github.com/Galooshi/import-js/blob/master/lib/visitIdentifierNodes.js).

**Comment by coagmano** [comment]
Why would you use object rest with destructured arguments when you aren't picking out other keys?

Isn't `test({ ...props }) {` equivalent to `test(props) {`?

**Comment by rivertam** [comment]
@coagmano this was a minimal example. I discovered it with other properties, but this is sufficiently a bug in that it's incorrect, but yes it's a general issue with object rest not just when it's alone.

**Comment by trotzig** [comment]
Thanks for the report and the minimal repro case. I have a fix on the way.
