### ISSUE TITLE
Best way to make a pull request to find package.josn

### ISSUE THREAD

**Issue by philolo1** [Galooshi/import-js#516]
Hi thanks for the great work. I use react-native and have multiple package.json, so the project gets confused. Right now i hard-code my path in `build/findProjectRoot.js` the correct path. I would like to do a PR, but I first want to discuss the approach. What do you think about using a projectRoot variable `.import-js` until another solution is found?

**Comment by trotzig** [comment]
Hi! There is a PR exploring this issue: https://github.com/Galooshi/import-js/pull/462. I don't think a `projectRoot` variable in .importjs.js would be sufficient. The proposed solution in #462 was originally to introduce an `isRoot` boolean in package.json files, and I think that might be the best solution. The only modification I'd like to see for that PR is nesting `isRoot` under `importjs`. So the package.json would look like this:

```json
{
  ...
  "importjs": {
    "isRoot": false
  },
  ...
}
```

Would you be able to pick up where that PR left off and introduce the "importjs" nesting?

**Comment by philolo1** [comment]
@trotzig thanks for the fast reply. Yes, that should be possible. I will create a new pr and let you know.

**Comment by philolo1** [comment]
closing the issue since its solved
