### ISSUE TITLE
React hooks not found

### ISSUE THREAD

**Issue by mikabytes** [Galooshi/import-js#526]
```
  const value = useContext(Context)
```

`useContext` doesn't get imported. If I use fixWord, it says **No JS module to import for `useContext`**

However when I add it manuallly all works just fine.

This is using React 16.7.0-alpha.2

**Comment by mikabytes** [comment]
Confirmed that specifying them manually in config solves the issue.

.importjs.js
```
module.exports = {
  namedExports: {
    'React': ['useState', 'useEffect', 'useContext', 'useReducer', 'useCallback', 'useMemo', 'useRef', 'useImperativeMethods', 'useLayoutEffect']
  }
}
```

**Comment by iahu** [comment]
can it just work as well, but not set the namedExports config ?

**Comment by mikabytes** [comment]
Well, not at the time when I created this issue. I have since stopped using React, so I don't know if it has been solved since then.

**Comment by mikabytes** [comment]
This is still an issue with React `18.2` and ImportJS `5.1`. It just can't determine that the `react` module exports those functions for some reason.

**Comment by mikabytes** [comment]
Pretty sure this is due to #344 

Closing this in favor of keeping discussion over there.
