### ISSUE TITLE
import * as d3 from 'd3'

### ISSUE THREAD

**Issue by jameskerr** [Galooshi/import-js#531]
I'm using d3 in a file and previously had code like this:

```
import * as d3 from "d3"

d3.select("svg")....
```

After running `importjs rewrite --overwrite <filename>`, my file looks like:

```
d3.select("svg")
```

It's missing the import statement. 

Is there some config I can set so that it knows to include d3 as an `import * as`?

**Comment by mikabytes** [comment]
Hi. I tried to reproduce this but couldn't. Is this still an issue for you?

I'll close this issue now as it is quite old, but if it still needs attention please re-open it. Thanks.
