### ISSUE TITLE
Is this module still supported?

### ISSUE THREAD

**Issue by mattnibs** [Galooshi/import-js#537]
Last update was a year ago...

**Comment by trotzig** [comment]
Hi @mattnibs! This library is not under active development right now, we've been busy with other things. But it's still a tool I use daily while writing code. We haven't been great at responding to issues in a while, it's hard to stay on top of open source projects. I hope you still find it usable, or come across a similar tool that can help you with the same tasks!

**Comment by mattnibs** [comment]
Thanks @trotzig. I hear you on staying on top of an open source project. This is a useful module! We've just been having issues with building this module in node v12 because of its dependency on an older version of sqlite3... I suppose I could put a pr to fix this.

**Comment by dagolinuxoid** [comment]
The module is awesome!!
