### ISSUE TITLE
groupImports ends up grouping namedExports separately.

### ISSUE THREAD

**Issue by spacesuitdiver** [Galooshi/import-js#561]
A configuration like:
```
    namedExports: {
        'foo': ['bar'],
    },
```

Nets us:

```
import React from 'react';

import { bar } from 'foo';

```

**Comment by mikabytes** [comment]
I believe this is a behavior as per design. I'll close this issue in any case as it is stale. If anyone feels this is something we should look more into, please reopen the issue. Thanks.
