### ISSUE TITLE
when i move a personal module file to an other folder, the import suggestion of the personal module propose the old folder and the new folder

### ISSUE THREAD

**Issue by mohamed-amine-haine** [Galooshi/import-js#579]
when i move a personal module file to an other folder, the import suggestion of the personal module propose the module in old folder and the new folder. i think it is a cache issue. when i close vs code and re open it. the import suggestion of the personal module propose only the module in the new folder. 

if there is a cache issue. quick solution, maybe allow to disable cache in extension conf.

**Comment by trotzig** [comment]
Are you using watchman by any chance? (see docs here: https://github.com/Galooshi/import-js#things-to-note)

I'm using watchman and haven't noticed this issue.

**Comment by mikabytes** [comment]
Hi @mohamed-amine-haine 

Is this still an issue?

I'm closing this for now due to inactivity, but please reopen if it's still a problem for you. Thanks.
