### ISSUE TITLE
Move to Prettier, abandon ESlint

### ISSUE THREAD

**Issue by mikabytes** [Galooshi/import-js#594]
Recently I made a pull request and hit several speedbumps due to convention issues. While this is perhaps not overly important, it is a bit of an annoyance. 

Me and my colleagues have used Prettier for the past several years and we have the feeling of "never, ever, going back". It fixes conventions automatically and ensures conformity. For me, it leads to developer bliss, whereas ESlint and such hinders flow.

Perhaps we could include it in this project also?

**Comment by mikabytes** [comment]
As a personal preference, I would recommend using Prettier defaults all except `semi: false`. Prettier makes it obvious wherever ASI fails, which is a rare occurance. Also, there's [the TypeScript aspect](https://medium.com/@eugenkiss/dont-use-semicolons-in-typescript-474ccfe4bdb3)

**Comment by trotzig** [comment]
Sounds good! I also prefer to use semicolons, so that would be a good config.

**Comment by mikabytes** [comment]
Great :)

But maybe I was unclear, I prefer _not_ to use semicolons. I know this is a heated debate in the community with strong opinions in both directions. I'm in camp "Don't add something useless if you don't have to". But I respect that others disagree, and seeing as the established convention is to use them, I can endure keeping them ;)

**Comment by trotzig** [comment]
Okay! You pick, as long as the config is there it’s going to be consistent anyway. 🙂👍
