### ISSUE TITLE
Cleaning up stale issues & PRs

### ISSUE THREAD

**Issue by mikabytes** [Galooshi/import-js#595]
What do you think about closing old ones that haven't seen any activity for a long time? Keeping them around makes it harder to distinguish what's active and worth looking into, whereas those that are out-of-date and no longer relevant.

They can be reopened at a later date if necessary.

We could have a policy to close ones that have not seen any activity for a certain time. Perhaps 3 months is sensible.

**Comment by trotzig** [comment]
Sounds good to me!

**Comment by mikabytes** [comment]
Closing this as discussion has concluded. It's a work in progress, likely will take a while :smile:
