### ISSUE TITLE
React Imports on JSX

### ISSUE THREAD

**Issue by mikabytes** [Galooshi/import-js#597]
There's a 2-year old PR #580 to _not_ add an import to React when using JSX and version 17 or later.

I'm thinking, only people who need that functionality uses a version of React that is 6 years old (or worse). Perhaps the more sensible thing to do is to remove that functionality altogether, rather than hacking into the package.json and disabling the behavior.

What do you think?

**Comment by trotzig** [comment]
Yeah seems like the right thing to do.
