### ISSUE TITLE
Add plugin support

### ISSUE THREAD

**Issue by mikabytes** [Galooshi/import-js#617]
We have several requests for the ability to modify how modules are mapped. A few related are: #555 #533 #556 #564 #522 #550 #520 #519

While it is unreasonable for ImportJS to support _everything_ out of the box, there are many cases where it is reasonable to support different behavior for specific projects.

It would also help to develop and collaborate on experimental features over a longer time before integrating them in the official build of ImportJS.

Minimal support:

- [ ] Adding identifiers given a file and AST
- [ ] Removing identifiers given a file, AST, and identifiers
- [ ] Globally adding files and identifiers outside the scope of ImportJS
- [ ] Adding configuration schemas (enables potential plugins such as ES2023, or a .babelrc reader, to configure `parserPlugins` for us)

Let's use this issue to discuss if and how to achieve this.

**Comment by lencioni** [comment]
It might be nice to move all of the meteor support into a plugin

**Comment by mikabytes** [comment]
Just saw another issue on the topic of plugins #490 

Closing this in favor of keeping discussion in the previous one.
