### ISSUE TITLE
Version bump request

### ISSUE THREAD

**Issue by simian-loco** [Galooshi/import-js#622]
Hello @trotzig ! First off thank you for this library, it has helped me immensely in the world of linux/vim/tsx.

I am wondering if you are open to bumping to v5.2.0 since the npm-published v5.1.0 does not include the change which stopped importing React every time.

Right now I am hard linking to the github hash so it is not an immediate issue for me... just thought I would post this as a low-hanging fruit item.

**Comment by mikabytes** [comment]
Hi @simian-loco. Thank you for the interest and the nudge :-) 

We're in the middle of making some other changes such as #623 and #608. Once that is all in place I expect we will see a new version deployed.

I'll close this issue for now, but please don't hesitate to reopen it if there's anything to add.

**Comment by lencioni** [comment]
v6.0.0 was just published
