### ISSUE TITLE
Running the Sublime plugin in Windows

### ISSUE THREAD

**Issue by trotzig** [Galooshi/import-js#99]
The ImportJS package in Package Control is only available to OSX users. I choose to make that limitation because I don't have a Linux or Windows environment available to test things in at the moment. 

@janpaul123, @shreeya, @kevinkehl, @lencioni: Does anyone have another environment than OSX where they would be willing to test import-js? I'd mainly like to see how the Sublime plugin works, but I guess it would be good to test the Emacs and vim plugins too if possible.

**Comment by kevinkehl** [comment]
Emacs plugin will work fine in Linux. Windows will work as well as using the shell works in Windows (meaning I have no idea if it will work or not). I don't have a Windows machine, but I'll try using the dev VMs they provide.

**Comment by vini175pa** [comment]
I'm using Linux Mint 64 Bit with Sublime Text 3083. And, apart of that problem i'm having (almost fixing it), it works pretty well.
I'll test it on Windows 10!

**Comment by trotzig** [comment]
Hey @vini175pa, that's probably why you didn't find it through Package Control. I only added osx to begin with, as I didn't have an opportunity to test other platforms. 

I've added Linux to the mix in this PR: https://github.com/wbond/package_control_channel/pull/5103

**Comment by trotzig** [comment]
I've done some initial testing on windows. The main blocker is that we rely on `find` and `egrep` when searching for js files matching a certain string. There are no direct equivalents on Windows (unless you install cygwin), so the `import-js` call fails. Initially, import-js searched files using `Dir.glob` directly in Ruby code. The switch to external `find` and `egrep` commands was done because it improved performance significantly. Though part of that performance win was because we used to look through the `node_modules` folder. Since we no longer do that, we might be able to get away with `Dir.glob` again.

**Comment by lencioni** [comment]
If `Dir.glob` is still too slow, we might want to consider doing OS detection and choosing whatever is best for the given OS. [This is the approach that Overcommit takes](https://github.com/brigade/overcommit/blob/282f569df/lib/overcommit/os.rb), [for instance](https://github.com/brigade/overcommit/blob/de5f0eb8cd/lib/overcommit/utils/file_utils.rb#L22-L25).

**Comment by lencioni** [comment]
https://github.com/facebook/jest/blob/052af961fb469f78ddcbd623b39622416fc21da9/packages/jest-haste-map/src/crawlers/node.js

**Comment by trotzig** [comment]
That looks like a good approach.

**Comment by lencioni** [comment]
Fixed by 0994bc3.
